// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/packetenrichment/v1/player.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.packetenrichment.v1;

@com.google.protobuf.Generated
public final class Player {
  private Player() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Player.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.packetenrichment.v1.PlayerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return Whether the playerUuid field is set.
     */
    boolean hasPlayerUuid();
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return The playerUuid.
     */
    lunarclient.apollo.common.v1.UuidOuterClass.Uuid getPlayerUuid();
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     */
    lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getPlayerUuidOrBuilder();

    /**
     * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
     * @return Whether the location field is set.
     */
    boolean hasLocation();
    /**
     * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
     * @return The location.
     */
    lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation getLocation();
    /**
     * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
     */
    lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocationOrBuilder getLocationOrBuilder();

    /**
     * <code>bool sneaking = 3 [json_name = "sneaking"];</code>
     * @return The sneaking.
     */
    boolean getSneaking();

    /**
     * <code>bool sprinting = 4 [json_name = "sprinting"];</code>
     * @return The sprinting.
     */
    boolean getSprinting();

    /**
     * <code>bool jumping = 5 [json_name = "jumping"];</code>
     * @return The jumping.
     */
    boolean getJumping();

    /**
     * <code>float forward_speed = 6 [json_name = "forwardSpeed"];</code>
     * @return The forwardSpeed.
     */
    float getForwardSpeed();

    /**
     * <code>float strafe_speed = 7 [json_name = "strafeSpeed"];</code>
     * @return The strafeSpeed.
     */
    float getStrafeSpeed();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.packetenrichment.v1.PlayerInfo}
   */
  public static final class PlayerInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.packetenrichment.v1.PlayerInfo)
      PlayerInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        PlayerInfo.class.getName());
    }
    // Use PlayerInfo.newBuilder() to construct.
    private PlayerInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlayerInfo() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.packetenrichment.v1.Player.internal_static_lunarclient_apollo_packetenrichment_v1_PlayerInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.packetenrichment.v1.Player.internal_static_lunarclient_apollo_packetenrichment_v1_PlayerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.class, lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYER_UUID_FIELD_NUMBER = 1;
    private lunarclient.apollo.common.v1.UuidOuterClass.Uuid playerUuid_;
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return Whether the playerUuid field is set.
     */
    @java.lang.Override
    public boolean hasPlayerUuid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return The playerUuid.
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.UuidOuterClass.Uuid getPlayerUuid() {
      return playerUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getPlayerUuidOrBuilder() {
      return playerUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
    }

    public static final int LOCATION_FIELD_NUMBER = 2;
    private lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation location_;
    /**
     * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
     * @return Whether the location field is set.
     */
    @java.lang.Override
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
     * @return The location.
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation getLocation() {
      return location_ == null ? lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.getDefaultInstance() : location_;
    }
    /**
     * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocationOrBuilder getLocationOrBuilder() {
      return location_ == null ? lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.getDefaultInstance() : location_;
    }

    public static final int SNEAKING_FIELD_NUMBER = 3;
    private boolean sneaking_ = false;
    /**
     * <code>bool sneaking = 3 [json_name = "sneaking"];</code>
     * @return The sneaking.
     */
    @java.lang.Override
    public boolean getSneaking() {
      return sneaking_;
    }

    public static final int SPRINTING_FIELD_NUMBER = 4;
    private boolean sprinting_ = false;
    /**
     * <code>bool sprinting = 4 [json_name = "sprinting"];</code>
     * @return The sprinting.
     */
    @java.lang.Override
    public boolean getSprinting() {
      return sprinting_;
    }

    public static final int JUMPING_FIELD_NUMBER = 5;
    private boolean jumping_ = false;
    /**
     * <code>bool jumping = 5 [json_name = "jumping"];</code>
     * @return The jumping.
     */
    @java.lang.Override
    public boolean getJumping() {
      return jumping_;
    }

    public static final int FORWARD_SPEED_FIELD_NUMBER = 6;
    private float forwardSpeed_ = 0F;
    /**
     * <code>float forward_speed = 6 [json_name = "forwardSpeed"];</code>
     * @return The forwardSpeed.
     */
    @java.lang.Override
    public float getForwardSpeed() {
      return forwardSpeed_;
    }

    public static final int STRAFE_SPEED_FIELD_NUMBER = 7;
    private float strafeSpeed_ = 0F;
    /**
     * <code>float strafe_speed = 7 [json_name = "strafeSpeed"];</code>
     * @return The strafeSpeed.
     */
    @java.lang.Override
    public float getStrafeSpeed() {
      return strafeSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getPlayerUuid());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getLocation());
      }
      if (sneaking_ != false) {
        output.writeBool(3, sneaking_);
      }
      if (sprinting_ != false) {
        output.writeBool(4, sprinting_);
      }
      if (jumping_ != false) {
        output.writeBool(5, jumping_);
      }
      if (java.lang.Float.floatToRawIntBits(forwardSpeed_) != 0) {
        output.writeFloat(6, forwardSpeed_);
      }
      if (java.lang.Float.floatToRawIntBits(strafeSpeed_) != 0) {
        output.writeFloat(7, strafeSpeed_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlayerUuid());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLocation());
      }
      if (sneaking_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, sneaking_);
      }
      if (sprinting_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, sprinting_);
      }
      if (jumping_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, jumping_);
      }
      if (java.lang.Float.floatToRawIntBits(forwardSpeed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, forwardSpeed_);
      }
      if (java.lang.Float.floatToRawIntBits(strafeSpeed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, strafeSpeed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo)) {
        return super.equals(obj);
      }
      lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo other = (lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo) obj;

      if (hasPlayerUuid() != other.hasPlayerUuid()) return false;
      if (hasPlayerUuid()) {
        if (!getPlayerUuid()
            .equals(other.getPlayerUuid())) return false;
      }
      if (hasLocation() != other.hasLocation()) return false;
      if (hasLocation()) {
        if (!getLocation()
            .equals(other.getLocation())) return false;
      }
      if (getSneaking()
          != other.getSneaking()) return false;
      if (getSprinting()
          != other.getSprinting()) return false;
      if (getJumping()
          != other.getJumping()) return false;
      if (java.lang.Float.floatToIntBits(getForwardSpeed())
          != java.lang.Float.floatToIntBits(
              other.getForwardSpeed())) return false;
      if (java.lang.Float.floatToIntBits(getStrafeSpeed())
          != java.lang.Float.floatToIntBits(
              other.getStrafeSpeed())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlayerUuid()) {
        hash = (37 * hash) + PLAYER_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerUuid().hashCode();
      }
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (37 * hash) + SNEAKING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSneaking());
      hash = (37 * hash) + SPRINTING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSprinting());
      hash = (37 * hash) + JUMPING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getJumping());
      hash = (37 * hash) + FORWARD_SPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getForwardSpeed());
      hash = (37 * hash) + STRAFE_SPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStrafeSpeed());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.packetenrichment.v1.PlayerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.packetenrichment.v1.PlayerInfo)
        lunarclient.apollo.packetenrichment.v1.Player.PlayerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.packetenrichment.v1.Player.internal_static_lunarclient_apollo_packetenrichment_v1_PlayerInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.packetenrichment.v1.Player.internal_static_lunarclient_apollo_packetenrichment_v1_PlayerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.class, lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.Builder.class);
      }

      // Construct using lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetPlayerUuidFieldBuilder();
          internalGetLocationFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        playerUuid_ = null;
        if (playerUuidBuilder_ != null) {
          playerUuidBuilder_.dispose();
          playerUuidBuilder_ = null;
        }
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        sneaking_ = false;
        sprinting_ = false;
        jumping_ = false;
        forwardSpeed_ = 0F;
        strafeSpeed_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.packetenrichment.v1.Player.internal_static_lunarclient_apollo_packetenrichment_v1_PlayerInfo_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo getDefaultInstanceForType() {
        return lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo build() {
        lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo buildPartial() {
        lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo result = new lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.playerUuid_ = playerUuidBuilder_ == null
              ? playerUuid_
              : playerUuidBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.location_ = locationBuilder_ == null
              ? location_
              : locationBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sneaking_ = sneaking_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sprinting_ = sprinting_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.jumping_ = jumping_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.forwardSpeed_ = forwardSpeed_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.strafeSpeed_ = strafeSpeed_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo) {
          return mergeFrom((lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo other) {
        if (other == lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.getDefaultInstance()) return this;
        if (other.hasPlayerUuid()) {
          mergePlayerUuid(other.getPlayerUuid());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (other.getSneaking() != false) {
          setSneaking(other.getSneaking());
        }
        if (other.getSprinting() != false) {
          setSprinting(other.getSprinting());
        }
        if (other.getJumping() != false) {
          setJumping(other.getJumping());
        }
        if (java.lang.Float.floatToRawIntBits(other.getForwardSpeed()) != 0) {
          setForwardSpeed(other.getForwardSpeed());
        }
        if (java.lang.Float.floatToRawIntBits(other.getStrafeSpeed()) != 0) {
          setStrafeSpeed(other.getStrafeSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetPlayerUuidFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    internalGetLocationFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                sneaking_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                sprinting_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                jumping_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 53: {
                forwardSpeed_ = input.readFloat();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              case 61: {
                strafeSpeed_ = input.readFloat();
                bitField0_ |= 0x00000040;
                break;
              } // case 61
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private lunarclient.apollo.common.v1.UuidOuterClass.Uuid playerUuid_;
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder> playerUuidBuilder_;
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       * @return Whether the playerUuid field is set.
       */
      public boolean hasPlayerUuid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       * @return The playerUuid.
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid getPlayerUuid() {
        if (playerUuidBuilder_ == null) {
          return playerUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
        } else {
          return playerUuidBuilder_.getMessage();
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder setPlayerUuid(lunarclient.apollo.common.v1.UuidOuterClass.Uuid value) {
        if (playerUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerUuid_ = value;
        } else {
          playerUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder setPlayerUuid(
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder builderForValue) {
        if (playerUuidBuilder_ == null) {
          playerUuid_ = builderForValue.build();
        } else {
          playerUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder mergePlayerUuid(lunarclient.apollo.common.v1.UuidOuterClass.Uuid value) {
        if (playerUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            playerUuid_ != null &&
            playerUuid_ != lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance()) {
            getPlayerUuidBuilder().mergeFrom(value);
          } else {
            playerUuid_ = value;
          }
        } else {
          playerUuidBuilder_.mergeFrom(value);
        }
        if (playerUuid_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder clearPlayerUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerUuid_ = null;
        if (playerUuidBuilder_ != null) {
          playerUuidBuilder_.dispose();
          playerUuidBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder getPlayerUuidBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetPlayerUuidFieldBuilder().getBuilder();
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getPlayerUuidOrBuilder() {
        if (playerUuidBuilder_ != null) {
          return playerUuidBuilder_.getMessageOrBuilder();
        } else {
          return playerUuid_ == null ?
              lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder> 
          internalGetPlayerUuidFieldBuilder() {
        if (playerUuidBuilder_ == null) {
          playerUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder>(
                  getPlayerUuid(),
                  getParentForChildren(),
                  isClean());
          playerUuid_ = null;
        }
        return playerUuidBuilder_;
      }

      private lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation location_;
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation, lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.Builder, lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocationOrBuilder> locationBuilder_;
      /**
       * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
       * @return Whether the location field is set.
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
       * @return The location.
       */
      public lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
       */
      public Builder setLocation(lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
       */
      public Builder setLocation(
          lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
       */
      public Builder mergeLocation(lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            location_ != null &&
            location_ != lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.getDefaultInstance()) {
            getLocationBuilder().mergeFrom(value);
          } else {
            location_ = value;
          }
        } else {
          locationBuilder_.mergeFrom(value);
        }
        if (location_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
       */
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
       */
      public lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.Builder getLocationBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return internalGetLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
       */
      public lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.PlayerLocation location = 2 [json_name = "location"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation, lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.Builder, lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocationOrBuilder> 
          internalGetLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation, lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.Builder, lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private boolean sneaking_ ;
      /**
       * <code>bool sneaking = 3 [json_name = "sneaking"];</code>
       * @return The sneaking.
       */
      @java.lang.Override
      public boolean getSneaking() {
        return sneaking_;
      }
      /**
       * <code>bool sneaking = 3 [json_name = "sneaking"];</code>
       * @param value The sneaking to set.
       * @return This builder for chaining.
       */
      public Builder setSneaking(boolean value) {

        sneaking_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool sneaking = 3 [json_name = "sneaking"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSneaking() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sneaking_ = false;
        onChanged();
        return this;
      }

      private boolean sprinting_ ;
      /**
       * <code>bool sprinting = 4 [json_name = "sprinting"];</code>
       * @return The sprinting.
       */
      @java.lang.Override
      public boolean getSprinting() {
        return sprinting_;
      }
      /**
       * <code>bool sprinting = 4 [json_name = "sprinting"];</code>
       * @param value The sprinting to set.
       * @return This builder for chaining.
       */
      public Builder setSprinting(boolean value) {

        sprinting_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool sprinting = 4 [json_name = "sprinting"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSprinting() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sprinting_ = false;
        onChanged();
        return this;
      }

      private boolean jumping_ ;
      /**
       * <code>bool jumping = 5 [json_name = "jumping"];</code>
       * @return The jumping.
       */
      @java.lang.Override
      public boolean getJumping() {
        return jumping_;
      }
      /**
       * <code>bool jumping = 5 [json_name = "jumping"];</code>
       * @param value The jumping to set.
       * @return This builder for chaining.
       */
      public Builder setJumping(boolean value) {

        jumping_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bool jumping = 5 [json_name = "jumping"];</code>
       * @return This builder for chaining.
       */
      public Builder clearJumping() {
        bitField0_ = (bitField0_ & ~0x00000010);
        jumping_ = false;
        onChanged();
        return this;
      }

      private float forwardSpeed_ ;
      /**
       * <code>float forward_speed = 6 [json_name = "forwardSpeed"];</code>
       * @return The forwardSpeed.
       */
      @java.lang.Override
      public float getForwardSpeed() {
        return forwardSpeed_;
      }
      /**
       * <code>float forward_speed = 6 [json_name = "forwardSpeed"];</code>
       * @param value The forwardSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setForwardSpeed(float value) {

        forwardSpeed_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>float forward_speed = 6 [json_name = "forwardSpeed"];</code>
       * @return This builder for chaining.
       */
      public Builder clearForwardSpeed() {
        bitField0_ = (bitField0_ & ~0x00000020);
        forwardSpeed_ = 0F;
        onChanged();
        return this;
      }

      private float strafeSpeed_ ;
      /**
       * <code>float strafe_speed = 7 [json_name = "strafeSpeed"];</code>
       * @return The strafeSpeed.
       */
      @java.lang.Override
      public float getStrafeSpeed() {
        return strafeSpeed_;
      }
      /**
       * <code>float strafe_speed = 7 [json_name = "strafeSpeed"];</code>
       * @param value The strafeSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setStrafeSpeed(float value) {

        strafeSpeed_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>float strafe_speed = 7 [json_name = "strafeSpeed"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStrafeSpeed() {
        bitField0_ = (bitField0_ & ~0x00000040);
        strafeSpeed_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.packetenrichment.v1.PlayerInfo)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.packetenrichment.v1.PlayerInfo)
    private static final lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo();
    }

    public static lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerInfo>
        PARSER = new com.google.protobuf.AbstractParser<PlayerInfo>() {
      @java.lang.Override
      public PlayerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlayerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_packetenrichment_v1_PlayerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_packetenrichment_v1_PlayerInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3lunarclient/apollo/packetenrichment/v1" +
      "/player.proto\022&lunarclient.apollo.packet" +
      "enrichment.v1\032+lunarclient/apollo/common" +
      "/v1/location.proto\032\'lunarclient/apollo/c" +
      "ommon/v1/uuid.proto\"\267\002\n\nPlayerInfo\022C\n\013pl" +
      "ayer_uuid\030\001 \001(\0132\".lunarclient.apollo.com" +
      "mon.v1.UuidR\nplayerUuid\022H\n\010location\030\002 \001(" +
      "\0132,.lunarclient.apollo.common.v1.PlayerL" +
      "ocationR\010location\022\032\n\010sneaking\030\003 \001(\010R\010sne" +
      "aking\022\034\n\tsprinting\030\004 \001(\010R\tsprinting\022\030\n\007j" +
      "umping\030\005 \001(\010R\007jumping\022#\n\rforward_speed\030\006" +
      " \001(\002R\014forwardSpeed\022!\n\014strafe_speed\030\007 \001(\002" +
      "R\013strafeSpeedb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          lunarclient.apollo.common.v1.LocationOuterClass.getDescriptor(),
          lunarclient.apollo.common.v1.UuidOuterClass.getDescriptor(),
        });
    internal_static_lunarclient_apollo_packetenrichment_v1_PlayerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_packetenrichment_v1_PlayerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_packetenrichment_v1_PlayerInfo_descriptor,
        new java.lang.String[] { "PlayerUuid", "Location", "Sneaking", "Sprinting", "Jumping", "ForwardSpeed", "StrafeSpeed", });
    descriptor.resolveAllFeaturesImmutable();
    lunarclient.apollo.common.v1.LocationOuterClass.getDescriptor();
    lunarclient.apollo.common.v1.UuidOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
