// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/packetenrichment/v1/world.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.packetenrichment.v1;

@com.google.protobuf.Generated
public final class World {
  private World() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      World.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerUseItemMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.packetenrichment.v1.PlayerUseItemMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
     * @return Whether the packetInfo field is set.
     */
    boolean hasPacketInfo();
    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
     * @return The packetInfo.
     */
    lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo getPacketInfo();
    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
     */
    lunarclient.apollo.packetenrichment.v1.Packet.PacketInfoOrBuilder getPacketInfoOrBuilder();

    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
     * @return Whether the playerInfo field is set.
     */
    boolean hasPlayerInfo();
    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
     * @return The playerInfo.
     */
    lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo getPlayerInfo();
    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
     */
    lunarclient.apollo.packetenrichment.v1.Player.PlayerInfoOrBuilder getPlayerInfoOrBuilder();

    /**
     * <code>bool main_hand = 3 [json_name = "mainHand"];</code>
     * @return The mainHand.
     */
    boolean getMainHand();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.packetenrichment.v1.PlayerUseItemMessage}
   */
  public static final class PlayerUseItemMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.packetenrichment.v1.PlayerUseItemMessage)
      PlayerUseItemMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        PlayerUseItemMessage.class.getName());
    }
    // Use PlayerUseItemMessage.newBuilder() to construct.
    private PlayerUseItemMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlayerUseItemMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.packetenrichment.v1.World.internal_static_lunarclient_apollo_packetenrichment_v1_PlayerUseItemMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.packetenrichment.v1.World.internal_static_lunarclient_apollo_packetenrichment_v1_PlayerUseItemMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage.class, lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage.Builder.class);
    }

    private int bitField0_;
    public static final int PACKET_INFO_FIELD_NUMBER = 1;
    private lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo packetInfo_;
    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
     * @return Whether the packetInfo field is set.
     */
    @java.lang.Override
    public boolean hasPacketInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
     * @return The packetInfo.
     */
    @java.lang.Override
    public lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo getPacketInfo() {
      return packetInfo_ == null ? lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo.getDefaultInstance() : packetInfo_;
    }
    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.packetenrichment.v1.Packet.PacketInfoOrBuilder getPacketInfoOrBuilder() {
      return packetInfo_ == null ? lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo.getDefaultInstance() : packetInfo_;
    }

    public static final int PLAYER_INFO_FIELD_NUMBER = 2;
    private lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo playerInfo_;
    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
     * @return Whether the playerInfo field is set.
     */
    @java.lang.Override
    public boolean hasPlayerInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
     * @return The playerInfo.
     */
    @java.lang.Override
    public lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo getPlayerInfo() {
      return playerInfo_ == null ? lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.getDefaultInstance() : playerInfo_;
    }
    /**
     * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.packetenrichment.v1.Player.PlayerInfoOrBuilder getPlayerInfoOrBuilder() {
      return playerInfo_ == null ? lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.getDefaultInstance() : playerInfo_;
    }

    public static final int MAIN_HAND_FIELD_NUMBER = 3;
    private boolean mainHand_ = false;
    /**
     * <code>bool main_hand = 3 [json_name = "mainHand"];</code>
     * @return The mainHand.
     */
    @java.lang.Override
    public boolean getMainHand() {
      return mainHand_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getPacketInfo());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getPlayerInfo());
      }
      if (mainHand_ != false) {
        output.writeBool(3, mainHand_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPacketInfo());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPlayerInfo());
      }
      if (mainHand_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, mainHand_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage other = (lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage) obj;

      if (hasPacketInfo() != other.hasPacketInfo()) return false;
      if (hasPacketInfo()) {
        if (!getPacketInfo()
            .equals(other.getPacketInfo())) return false;
      }
      if (hasPlayerInfo() != other.hasPlayerInfo()) return false;
      if (hasPlayerInfo()) {
        if (!getPlayerInfo()
            .equals(other.getPlayerInfo())) return false;
      }
      if (getMainHand()
          != other.getMainHand()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPacketInfo()) {
        hash = (37 * hash) + PACKET_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getPacketInfo().hashCode();
      }
      if (hasPlayerInfo()) {
        hash = (37 * hash) + PLAYER_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerInfo().hashCode();
      }
      hash = (37 * hash) + MAIN_HAND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMainHand());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.packetenrichment.v1.PlayerUseItemMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.packetenrichment.v1.PlayerUseItemMessage)
        lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.packetenrichment.v1.World.internal_static_lunarclient_apollo_packetenrichment_v1_PlayerUseItemMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.packetenrichment.v1.World.internal_static_lunarclient_apollo_packetenrichment_v1_PlayerUseItemMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage.class, lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetPacketInfoFieldBuilder();
          internalGetPlayerInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        packetInfo_ = null;
        if (packetInfoBuilder_ != null) {
          packetInfoBuilder_.dispose();
          packetInfoBuilder_ = null;
        }
        playerInfo_ = null;
        if (playerInfoBuilder_ != null) {
          playerInfoBuilder_.dispose();
          playerInfoBuilder_ = null;
        }
        mainHand_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.packetenrichment.v1.World.internal_static_lunarclient_apollo_packetenrichment_v1_PlayerUseItemMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage getDefaultInstanceForType() {
        return lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage build() {
        lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage buildPartial() {
        lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage result = new lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.packetInfo_ = packetInfoBuilder_ == null
              ? packetInfo_
              : packetInfoBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.playerInfo_ = playerInfoBuilder_ == null
              ? playerInfo_
              : playerInfoBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.mainHand_ = mainHand_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage) {
          return mergeFrom((lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage other) {
        if (other == lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage.getDefaultInstance()) return this;
        if (other.hasPacketInfo()) {
          mergePacketInfo(other.getPacketInfo());
        }
        if (other.hasPlayerInfo()) {
          mergePlayerInfo(other.getPlayerInfo());
        }
        if (other.getMainHand() != false) {
          setMainHand(other.getMainHand());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetPacketInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    internalGetPlayerInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                mainHand_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo packetInfo_;
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo, lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo.Builder, lunarclient.apollo.packetenrichment.v1.Packet.PacketInfoOrBuilder> packetInfoBuilder_;
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
       * @return Whether the packetInfo field is set.
       */
      public boolean hasPacketInfo() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
       * @return The packetInfo.
       */
      public lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo getPacketInfo() {
        if (packetInfoBuilder_ == null) {
          return packetInfo_ == null ? lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo.getDefaultInstance() : packetInfo_;
        } else {
          return packetInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
       */
      public Builder setPacketInfo(lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo value) {
        if (packetInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          packetInfo_ = value;
        } else {
          packetInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
       */
      public Builder setPacketInfo(
          lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo.Builder builderForValue) {
        if (packetInfoBuilder_ == null) {
          packetInfo_ = builderForValue.build();
        } else {
          packetInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
       */
      public Builder mergePacketInfo(lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo value) {
        if (packetInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            packetInfo_ != null &&
            packetInfo_ != lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo.getDefaultInstance()) {
            getPacketInfoBuilder().mergeFrom(value);
          } else {
            packetInfo_ = value;
          }
        } else {
          packetInfoBuilder_.mergeFrom(value);
        }
        if (packetInfo_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
       */
      public Builder clearPacketInfo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packetInfo_ = null;
        if (packetInfoBuilder_ != null) {
          packetInfoBuilder_.dispose();
          packetInfoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
       */
      public lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo.Builder getPacketInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetPacketInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
       */
      public lunarclient.apollo.packetenrichment.v1.Packet.PacketInfoOrBuilder getPacketInfoOrBuilder() {
        if (packetInfoBuilder_ != null) {
          return packetInfoBuilder_.getMessageOrBuilder();
        } else {
          return packetInfo_ == null ?
              lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo.getDefaultInstance() : packetInfo_;
        }
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PacketInfo packet_info = 1 [json_name = "packetInfo"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo, lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo.Builder, lunarclient.apollo.packetenrichment.v1.Packet.PacketInfoOrBuilder> 
          internalGetPacketInfoFieldBuilder() {
        if (packetInfoBuilder_ == null) {
          packetInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo, lunarclient.apollo.packetenrichment.v1.Packet.PacketInfo.Builder, lunarclient.apollo.packetenrichment.v1.Packet.PacketInfoOrBuilder>(
                  getPacketInfo(),
                  getParentForChildren(),
                  isClean());
          packetInfo_ = null;
        }
        return packetInfoBuilder_;
      }

      private lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo playerInfo_;
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo, lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.Builder, lunarclient.apollo.packetenrichment.v1.Player.PlayerInfoOrBuilder> playerInfoBuilder_;
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
       * @return Whether the playerInfo field is set.
       */
      public boolean hasPlayerInfo() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
       * @return The playerInfo.
       */
      public lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo getPlayerInfo() {
        if (playerInfoBuilder_ == null) {
          return playerInfo_ == null ? lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.getDefaultInstance() : playerInfo_;
        } else {
          return playerInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
       */
      public Builder setPlayerInfo(lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo value) {
        if (playerInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerInfo_ = value;
        } else {
          playerInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
       */
      public Builder setPlayerInfo(
          lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.Builder builderForValue) {
        if (playerInfoBuilder_ == null) {
          playerInfo_ = builderForValue.build();
        } else {
          playerInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
       */
      public Builder mergePlayerInfo(lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo value) {
        if (playerInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            playerInfo_ != null &&
            playerInfo_ != lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.getDefaultInstance()) {
            getPlayerInfoBuilder().mergeFrom(value);
          } else {
            playerInfo_ = value;
          }
        } else {
          playerInfoBuilder_.mergeFrom(value);
        }
        if (playerInfo_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
       */
      public Builder clearPlayerInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerInfo_ = null;
        if (playerInfoBuilder_ != null) {
          playerInfoBuilder_.dispose();
          playerInfoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
       */
      public lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.Builder getPlayerInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return internalGetPlayerInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
       */
      public lunarclient.apollo.packetenrichment.v1.Player.PlayerInfoOrBuilder getPlayerInfoOrBuilder() {
        if (playerInfoBuilder_ != null) {
          return playerInfoBuilder_.getMessageOrBuilder();
        } else {
          return playerInfo_ == null ?
              lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.getDefaultInstance() : playerInfo_;
        }
      }
      /**
       * <code>.lunarclient.apollo.packetenrichment.v1.PlayerInfo player_info = 2 [json_name = "playerInfo"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo, lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.Builder, lunarclient.apollo.packetenrichment.v1.Player.PlayerInfoOrBuilder> 
          internalGetPlayerInfoFieldBuilder() {
        if (playerInfoBuilder_ == null) {
          playerInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo, lunarclient.apollo.packetenrichment.v1.Player.PlayerInfo.Builder, lunarclient.apollo.packetenrichment.v1.Player.PlayerInfoOrBuilder>(
                  getPlayerInfo(),
                  getParentForChildren(),
                  isClean());
          playerInfo_ = null;
        }
        return playerInfoBuilder_;
      }

      private boolean mainHand_ ;
      /**
       * <code>bool main_hand = 3 [json_name = "mainHand"];</code>
       * @return The mainHand.
       */
      @java.lang.Override
      public boolean getMainHand() {
        return mainHand_;
      }
      /**
       * <code>bool main_hand = 3 [json_name = "mainHand"];</code>
       * @param value The mainHand to set.
       * @return This builder for chaining.
       */
      public Builder setMainHand(boolean value) {

        mainHand_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool main_hand = 3 [json_name = "mainHand"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMainHand() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mainHand_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.packetenrichment.v1.PlayerUseItemMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.packetenrichment.v1.PlayerUseItemMessage)
    private static final lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage();
    }

    public static lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerUseItemMessage>
        PARSER = new com.google.protobuf.AbstractParser<PlayerUseItemMessage>() {
      @java.lang.Override
      public PlayerUseItemMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlayerUseItemMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerUseItemMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.packetenrichment.v1.World.PlayerUseItemMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_packetenrichment_v1_PlayerUseItemMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_packetenrichment_v1_PlayerUseItemMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2lunarclient/apollo/packetenrichment/v1" +
      "/world.proto\022&lunarclient.apollo.packete" +
      "nrichment.v1\0323lunarclient/apollo/packete" +
      "nrichment/v1/packet.proto\0323lunarclient/a" +
      "pollo/packetenrichment/v1/player.proto\"\335" +
      "\001\n\024PlayerUseItemMessage\022S\n\013packet_info\030\001" +
      " \001(\01322.lunarclient.apollo.packetenrichme" +
      "nt.v1.PacketInfoR\npacketInfo\022S\n\013player_i" +
      "nfo\030\002 \001(\01322.lunarclient.apollo.packetenr" +
      "ichment.v1.PlayerInfoR\nplayerInfo\022\033\n\tmai" +
      "n_hand\030\003 \001(\010R\010mainHandb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          lunarclient.apollo.packetenrichment.v1.Packet.getDescriptor(),
          lunarclient.apollo.packetenrichment.v1.Player.getDescriptor(),
        });
    internal_static_lunarclient_apollo_packetenrichment_v1_PlayerUseItemMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_packetenrichment_v1_PlayerUseItemMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_packetenrichment_v1_PlayerUseItemMessage_descriptor,
        new java.lang.String[] { "PacketInfo", "PlayerInfo", "MainHand", });
    descriptor.resolveAllFeaturesImmutable();
    lunarclient.apollo.packetenrichment.v1.Packet.getDescriptor();
    lunarclient.apollo.packetenrichment.v1.Player.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
