// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/nametag/v1/schema.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.nametag.v1;

@com.google.protobuf.Generated
public final class Schema {
  private Schema() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Schema.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OverrideNametagMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.nametag.v1.OverrideNametagMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return Whether the playerUuid field is set.
     */
    boolean hasPlayerUuid();
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return The playerUuid.
     */
    lunarclient.apollo.common.v1.UuidOuterClass.Uuid getPlayerUuid();
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     */
    lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getPlayerUuidOrBuilder();

    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
     */
    @java.lang.Deprecated java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component> 
        getLinesList();
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
     */
    @java.lang.Deprecated lunarclient.apollo.common.v1.ComponentOuterClass.Component getLines(int index);
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
     */
    @java.lang.Deprecated int getLinesCount();
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
     */
    @java.lang.Deprecated java.util.List<? extends lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder> 
        getLinesOrBuilderList();
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
     */
    @java.lang.Deprecated lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder getLinesOrBuilder(
        int index);

    /**
     * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
     * @return A list containing the adventureJsonLines.
     */
    java.util.List<java.lang.String>
        getAdventureJsonLinesList();
    /**
     * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
     * @return The count of adventureJsonLines.
     */
    int getAdventureJsonLinesCount();
    /**
     * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
     * @param index The index of the element to return.
     * @return The adventureJsonLines at the given index.
     */
    java.lang.String getAdventureJsonLines(int index);
    /**
     * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the adventureJsonLines at the given index.
     */
    com.google.protobuf.ByteString
        getAdventureJsonLinesBytes(int index);
  }
  /**
   * Protobuf type {@code lunarclient.apollo.nametag.v1.OverrideNametagMessage}
   */
  public static final class OverrideNametagMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.nametag.v1.OverrideNametagMessage)
      OverrideNametagMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        OverrideNametagMessage.class.getName());
    }
    // Use OverrideNametagMessage.newBuilder() to construct.
    private OverrideNametagMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OverrideNametagMessage() {
      lines_ = java.util.Collections.emptyList();
      adventureJsonLines_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_OverrideNametagMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_OverrideNametagMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage.class, lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYER_UUID_FIELD_NUMBER = 1;
    private lunarclient.apollo.common.v1.UuidOuterClass.Uuid playerUuid_;
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return Whether the playerUuid field is set.
     */
    @java.lang.Override
    public boolean hasPlayerUuid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return The playerUuid.
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.UuidOuterClass.Uuid getPlayerUuid() {
      return playerUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getPlayerUuidOrBuilder() {
      return playerUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
    }

    public static final int LINES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component> lines_;
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
     */
    @java.lang.Override
    @java.lang.Deprecated public java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component> getLinesList() {
      return lines_;
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
     */
    @java.lang.Override
    @java.lang.Deprecated public java.util.List<? extends lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder> 
        getLinesOrBuilderList() {
      return lines_;
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
     */
    @java.lang.Override
    @java.lang.Deprecated public int getLinesCount() {
      return lines_.size();
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
     */
    @java.lang.Override
    @java.lang.Deprecated public lunarclient.apollo.common.v1.ComponentOuterClass.Component getLines(int index) {
      return lines_.get(index);
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
     */
    @java.lang.Override
    @java.lang.Deprecated public lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder getLinesOrBuilder(
        int index) {
      return lines_.get(index);
    }

    public static final int ADVENTURE_JSON_LINES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList adventureJsonLines_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
     * @return A list containing the adventureJsonLines.
     */
    public com.google.protobuf.ProtocolStringList
        getAdventureJsonLinesList() {
      return adventureJsonLines_;
    }
    /**
     * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
     * @return The count of adventureJsonLines.
     */
    public int getAdventureJsonLinesCount() {
      return adventureJsonLines_.size();
    }
    /**
     * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
     * @param index The index of the element to return.
     * @return The adventureJsonLines at the given index.
     */
    public java.lang.String getAdventureJsonLines(int index) {
      return adventureJsonLines_.get(index);
    }
    /**
     * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the adventureJsonLines at the given index.
     */
    public com.google.protobuf.ByteString
        getAdventureJsonLinesBytes(int index) {
      return adventureJsonLines_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getPlayerUuid());
      }
      for (int i = 0; i < lines_.size(); i++) {
        output.writeMessage(2, lines_.get(i));
      }
      for (int i = 0; i < adventureJsonLines_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, adventureJsonLines_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlayerUuid());
      }
      for (int i = 0; i < lines_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, lines_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < adventureJsonLines_.size(); i++) {
          dataSize += computeStringSizeNoTag(adventureJsonLines_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAdventureJsonLinesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage other = (lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage) obj;

      if (hasPlayerUuid() != other.hasPlayerUuid()) return false;
      if (hasPlayerUuid()) {
        if (!getPlayerUuid()
            .equals(other.getPlayerUuid())) return false;
      }
      if (!getLinesList()
          .equals(other.getLinesList())) return false;
      if (!getAdventureJsonLinesList()
          .equals(other.getAdventureJsonLinesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlayerUuid()) {
        hash = (37 * hash) + PLAYER_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerUuid().hashCode();
      }
      if (getLinesCount() > 0) {
        hash = (37 * hash) + LINES_FIELD_NUMBER;
        hash = (53 * hash) + getLinesList().hashCode();
      }
      if (getAdventureJsonLinesCount() > 0) {
        hash = (37 * hash) + ADVENTURE_JSON_LINES_FIELD_NUMBER;
        hash = (53 * hash) + getAdventureJsonLinesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.nametag.v1.OverrideNametagMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.nametag.v1.OverrideNametagMessage)
        lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_OverrideNametagMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_OverrideNametagMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage.class, lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetPlayerUuidFieldBuilder();
          internalGetLinesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        playerUuid_ = null;
        if (playerUuidBuilder_ != null) {
          playerUuidBuilder_.dispose();
          playerUuidBuilder_ = null;
        }
        if (linesBuilder_ == null) {
          lines_ = java.util.Collections.emptyList();
        } else {
          lines_ = null;
          linesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        adventureJsonLines_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_OverrideNametagMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage getDefaultInstanceForType() {
        return lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage build() {
        lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage buildPartial() {
        lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage result = new lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage result) {
        if (linesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            lines_ = java.util.Collections.unmodifiableList(lines_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.lines_ = lines_;
        } else {
          result.lines_ = linesBuilder_.build();
        }
      }

      private void buildPartial0(lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.playerUuid_ = playerUuidBuilder_ == null
              ? playerUuid_
              : playerUuidBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          adventureJsonLines_.makeImmutable();
          result.adventureJsonLines_ = adventureJsonLines_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage) {
          return mergeFrom((lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage other) {
        if (other == lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage.getDefaultInstance()) return this;
        if (other.hasPlayerUuid()) {
          mergePlayerUuid(other.getPlayerUuid());
        }
        if (linesBuilder_ == null) {
          if (!other.lines_.isEmpty()) {
            if (lines_.isEmpty()) {
              lines_ = other.lines_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLinesIsMutable();
              lines_.addAll(other.lines_);
            }
            onChanged();
          }
        } else {
          if (!other.lines_.isEmpty()) {
            if (linesBuilder_.isEmpty()) {
              linesBuilder_.dispose();
              linesBuilder_ = null;
              lines_ = other.lines_;
              bitField0_ = (bitField0_ & ~0x00000002);
              linesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetLinesFieldBuilder() : null;
            } else {
              linesBuilder_.addAllMessages(other.lines_);
            }
          }
        }
        if (!other.adventureJsonLines_.isEmpty()) {
          if (adventureJsonLines_.isEmpty()) {
            adventureJsonLines_ = other.adventureJsonLines_;
            bitField0_ |= 0x00000004;
          } else {
            ensureAdventureJsonLinesIsMutable();
            adventureJsonLines_.addAll(other.adventureJsonLines_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetPlayerUuidFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                lunarclient.apollo.common.v1.ComponentOuterClass.Component m =
                    input.readMessage(
                        lunarclient.apollo.common.v1.ComponentOuterClass.Component.parser(),
                        extensionRegistry);
                if (linesBuilder_ == null) {
                  ensureLinesIsMutable();
                  lines_.add(m);
                } else {
                  linesBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureAdventureJsonLinesIsMutable();
                adventureJsonLines_.add(s);
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private lunarclient.apollo.common.v1.UuidOuterClass.Uuid playerUuid_;
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder> playerUuidBuilder_;
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       * @return Whether the playerUuid field is set.
       */
      public boolean hasPlayerUuid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       * @return The playerUuid.
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid getPlayerUuid() {
        if (playerUuidBuilder_ == null) {
          return playerUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
        } else {
          return playerUuidBuilder_.getMessage();
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder setPlayerUuid(lunarclient.apollo.common.v1.UuidOuterClass.Uuid value) {
        if (playerUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerUuid_ = value;
        } else {
          playerUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder setPlayerUuid(
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder builderForValue) {
        if (playerUuidBuilder_ == null) {
          playerUuid_ = builderForValue.build();
        } else {
          playerUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder mergePlayerUuid(lunarclient.apollo.common.v1.UuidOuterClass.Uuid value) {
        if (playerUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            playerUuid_ != null &&
            playerUuid_ != lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance()) {
            getPlayerUuidBuilder().mergeFrom(value);
          } else {
            playerUuid_ = value;
          }
        } else {
          playerUuidBuilder_.mergeFrom(value);
        }
        if (playerUuid_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder clearPlayerUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerUuid_ = null;
        if (playerUuidBuilder_ != null) {
          playerUuidBuilder_.dispose();
          playerUuidBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder getPlayerUuidBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetPlayerUuidFieldBuilder().getBuilder();
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getPlayerUuidOrBuilder() {
        if (playerUuidBuilder_ != null) {
          return playerUuidBuilder_.getMessageOrBuilder();
        } else {
          return playerUuid_ == null ?
              lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder> 
          internalGetPlayerUuidFieldBuilder() {
        if (playerUuidBuilder_ == null) {
          playerUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder>(
                  getPlayerUuid(),
                  getParentForChildren(),
                  isClean());
          playerUuid_ = null;
        }
        return playerUuidBuilder_;
      }

      private java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component> lines_ =
        java.util.Collections.emptyList();
      private void ensureLinesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          lines_ = new java.util.ArrayList<lunarclient.apollo.common.v1.ComponentOuterClass.Component>(lines_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          lunarclient.apollo.common.v1.ComponentOuterClass.Component, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder, lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder> linesBuilder_;

      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component> getLinesList() {
        if (linesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lines_);
        } else {
          return linesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public int getLinesCount() {
        if (linesBuilder_ == null) {
          return lines_.size();
        } else {
          return linesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public lunarclient.apollo.common.v1.ComponentOuterClass.Component getLines(int index) {
        if (linesBuilder_ == null) {
          return lines_.get(index);
        } else {
          return linesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setLines(
          int index, lunarclient.apollo.common.v1.ComponentOuterClass.Component value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.set(index, value);
          onChanged();
        } else {
          linesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setLines(
          int index, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.set(index, builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder addLines(lunarclient.apollo.common.v1.ComponentOuterClass.Component value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.add(value);
          onChanged();
        } else {
          linesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder addLines(
          int index, lunarclient.apollo.common.v1.ComponentOuterClass.Component value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.add(index, value);
          onChanged();
        } else {
          linesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder addLines(
          lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.add(builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder addLines(
          int index, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.add(index, builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder addAllLines(
          java.lang.Iterable<? extends lunarclient.apollo.common.v1.ComponentOuterClass.Component> values) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, lines_);
          onChanged();
        } else {
          linesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder clearLines() {
        if (linesBuilder_ == null) {
          lines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          linesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder removeLines(int index) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.remove(index);
          onChanged();
        } else {
          linesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder getLinesBuilder(
          int index) {
        return internalGetLinesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder getLinesOrBuilder(
          int index) {
        if (linesBuilder_ == null) {
          return lines_.get(index);  } else {
          return linesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public java.util.List<? extends lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder> 
           getLinesOrBuilderList() {
        if (linesBuilder_ != null) {
          return linesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lines_);
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder addLinesBuilder() {
        return internalGetLinesFieldBuilder().addBuilder(
            lunarclient.apollo.common.v1.ComponentOuterClass.Component.getDefaultInstance());
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder addLinesBuilder(
          int index) {
        return internalGetLinesFieldBuilder().addBuilder(
            index, lunarclient.apollo.common.v1.ComponentOuterClass.Component.getDefaultInstance());
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component lines = 2 [json_name = "lines", deprecated = true];</code>
       */
      @java.lang.Deprecated public java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder> 
           getLinesBuilderList() {
        return internalGetLinesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          lunarclient.apollo.common.v1.ComponentOuterClass.Component, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder, lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder> 
          internalGetLinesFieldBuilder() {
        if (linesBuilder_ == null) {
          linesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              lunarclient.apollo.common.v1.ComponentOuterClass.Component, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder, lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder>(
                  lines_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          lines_ = null;
        }
        return linesBuilder_;
      }

      private com.google.protobuf.LazyStringArrayList adventureJsonLines_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureAdventureJsonLinesIsMutable() {
        if (!adventureJsonLines_.isModifiable()) {
          adventureJsonLines_ = new com.google.protobuf.LazyStringArrayList(adventureJsonLines_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
       * @return A list containing the adventureJsonLines.
       */
      public com.google.protobuf.ProtocolStringList
          getAdventureJsonLinesList() {
        adventureJsonLines_.makeImmutable();
        return adventureJsonLines_;
      }
      /**
       * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
       * @return The count of adventureJsonLines.
       */
      public int getAdventureJsonLinesCount() {
        return adventureJsonLines_.size();
      }
      /**
       * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
       * @param index The index of the element to return.
       * @return The adventureJsonLines at the given index.
       */
      public java.lang.String getAdventureJsonLines(int index) {
        return adventureJsonLines_.get(index);
      }
      /**
       * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
       * @param index The index of the value to return.
       * @return The bytes of the adventureJsonLines at the given index.
       */
      public com.google.protobuf.ByteString
          getAdventureJsonLinesBytes(int index) {
        return adventureJsonLines_.getByteString(index);
      }
      /**
       * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
       * @param index The index to set the value at.
       * @param value The adventureJsonLines to set.
       * @return This builder for chaining.
       */
      public Builder setAdventureJsonLines(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureAdventureJsonLinesIsMutable();
        adventureJsonLines_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
       * @param value The adventureJsonLines to add.
       * @return This builder for chaining.
       */
      public Builder addAdventureJsonLines(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureAdventureJsonLinesIsMutable();
        adventureJsonLines_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
       * @param values The adventureJsonLines to add.
       * @return This builder for chaining.
       */
      public Builder addAllAdventureJsonLines(
          java.lang.Iterable<java.lang.String> values) {
        ensureAdventureJsonLinesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, adventureJsonLines_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAdventureJsonLines() {
        adventureJsonLines_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adventure_json_lines = 3 [json_name = "adventureJsonLines"];</code>
       * @param value The bytes of the adventureJsonLines to add.
       * @return This builder for chaining.
       */
      public Builder addAdventureJsonLinesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureAdventureJsonLinesIsMutable();
        adventureJsonLines_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.nametag.v1.OverrideNametagMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.nametag.v1.OverrideNametagMessage)
    private static final lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage();
    }

    public static lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OverrideNametagMessage>
        PARSER = new com.google.protobuf.AbstractParser<OverrideNametagMessage>() {
      @java.lang.Override
      public OverrideNametagMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OverrideNametagMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OverrideNametagMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.nametag.v1.Schema.OverrideNametagMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResetNametagMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.nametag.v1.ResetNametagMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return Whether the playerUuid field is set.
     */
    boolean hasPlayerUuid();
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return The playerUuid.
     */
    lunarclient.apollo.common.v1.UuidOuterClass.Uuid getPlayerUuid();
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     */
    lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getPlayerUuidOrBuilder();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.nametag.v1.ResetNametagMessage}
   */
  public static final class ResetNametagMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.nametag.v1.ResetNametagMessage)
      ResetNametagMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ResetNametagMessage.class.getName());
    }
    // Use ResetNametagMessage.newBuilder() to construct.
    private ResetNametagMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResetNametagMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_ResetNametagMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_ResetNametagMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage.class, lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYER_UUID_FIELD_NUMBER = 1;
    private lunarclient.apollo.common.v1.UuidOuterClass.Uuid playerUuid_;
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return Whether the playerUuid field is set.
     */
    @java.lang.Override
    public boolean hasPlayerUuid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     * @return The playerUuid.
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.UuidOuterClass.Uuid getPlayerUuid() {
      return playerUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getPlayerUuidOrBuilder() {
      return playerUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getPlayerUuid());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlayerUuid());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage other = (lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage) obj;

      if (hasPlayerUuid() != other.hasPlayerUuid()) return false;
      if (hasPlayerUuid()) {
        if (!getPlayerUuid()
            .equals(other.getPlayerUuid())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlayerUuid()) {
        hash = (37 * hash) + PLAYER_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerUuid().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.nametag.v1.ResetNametagMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.nametag.v1.ResetNametagMessage)
        lunarclient.apollo.nametag.v1.Schema.ResetNametagMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_ResetNametagMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_ResetNametagMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage.class, lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetPlayerUuidFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        playerUuid_ = null;
        if (playerUuidBuilder_ != null) {
          playerUuidBuilder_.dispose();
          playerUuidBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_ResetNametagMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage getDefaultInstanceForType() {
        return lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage build() {
        lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage buildPartial() {
        lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage result = new lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.playerUuid_ = playerUuidBuilder_ == null
              ? playerUuid_
              : playerUuidBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage) {
          return mergeFrom((lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage other) {
        if (other == lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage.getDefaultInstance()) return this;
        if (other.hasPlayerUuid()) {
          mergePlayerUuid(other.getPlayerUuid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetPlayerUuidFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private lunarclient.apollo.common.v1.UuidOuterClass.Uuid playerUuid_;
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder> playerUuidBuilder_;
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       * @return Whether the playerUuid field is set.
       */
      public boolean hasPlayerUuid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       * @return The playerUuid.
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid getPlayerUuid() {
        if (playerUuidBuilder_ == null) {
          return playerUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
        } else {
          return playerUuidBuilder_.getMessage();
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder setPlayerUuid(lunarclient.apollo.common.v1.UuidOuterClass.Uuid value) {
        if (playerUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerUuid_ = value;
        } else {
          playerUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder setPlayerUuid(
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder builderForValue) {
        if (playerUuidBuilder_ == null) {
          playerUuid_ = builderForValue.build();
        } else {
          playerUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder mergePlayerUuid(lunarclient.apollo.common.v1.UuidOuterClass.Uuid value) {
        if (playerUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            playerUuid_ != null &&
            playerUuid_ != lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance()) {
            getPlayerUuidBuilder().mergeFrom(value);
          } else {
            playerUuid_ = value;
          }
        } else {
          playerUuidBuilder_.mergeFrom(value);
        }
        if (playerUuid_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public Builder clearPlayerUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerUuid_ = null;
        if (playerUuidBuilder_ != null) {
          playerUuidBuilder_.dispose();
          playerUuidBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder getPlayerUuidBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetPlayerUuidFieldBuilder().getBuilder();
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getPlayerUuidOrBuilder() {
        if (playerUuidBuilder_ != null) {
          return playerUuidBuilder_.getMessageOrBuilder();
        } else {
          return playerUuid_ == null ?
              lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : playerUuid_;
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid player_uuid = 1 [json_name = "playerUuid"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder> 
          internalGetPlayerUuidFieldBuilder() {
        if (playerUuidBuilder_ == null) {
          playerUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder>(
                  getPlayerUuid(),
                  getParentForChildren(),
                  isClean());
          playerUuid_ = null;
        }
        return playerUuidBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.nametag.v1.ResetNametagMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.nametag.v1.ResetNametagMessage)
    private static final lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage();
    }

    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResetNametagMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResetNametagMessage>() {
      @java.lang.Override
      public ResetNametagMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResetNametagMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResetNametagMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.nametag.v1.Schema.ResetNametagMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResetNametagsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.nametag.v1.ResetNametagsMessage)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * nothing
   * </pre>
   *
   * Protobuf type {@code lunarclient.apollo.nametag.v1.ResetNametagsMessage}
   */
  public static final class ResetNametagsMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.nametag.v1.ResetNametagsMessage)
      ResetNametagsMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ResetNametagsMessage.class.getName());
    }
    // Use ResetNametagsMessage.newBuilder() to construct.
    private ResetNametagsMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResetNametagsMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_ResetNametagsMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_ResetNametagsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage.class, lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage other = (lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * nothing
     * </pre>
     *
     * Protobuf type {@code lunarclient.apollo.nametag.v1.ResetNametagsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.nametag.v1.ResetNametagsMessage)
        lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_ResetNametagsMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_ResetNametagsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage.class, lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.nametag.v1.Schema.internal_static_lunarclient_apollo_nametag_v1_ResetNametagsMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage getDefaultInstanceForType() {
        return lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage build() {
        lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage buildPartial() {
        lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage result = new lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage) {
          return mergeFrom((lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage other) {
        if (other == lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.nametag.v1.ResetNametagsMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.nametag.v1.ResetNametagsMessage)
    private static final lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage();
    }

    public static lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResetNametagsMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResetNametagsMessage>() {
      @java.lang.Override
      public ResetNametagsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResetNametagsMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResetNametagsMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.nametag.v1.Schema.ResetNametagsMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_nametag_v1_OverrideNametagMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_nametag_v1_OverrideNametagMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_nametag_v1_ResetNametagMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_nametag_v1_ResetNametagMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_nametag_v1_ResetNametagsMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_nametag_v1_ResetNametagsMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*lunarclient/apollo/nametag/v1/schema.p" +
      "roto\022\035lunarclient.apollo.nametag.v1\032,lun" +
      "arclient/apollo/common/v1/component.prot" +
      "o\032\'lunarclient/apollo/common/v1/uuid.pro" +
      "to\"\322\001\n\026OverrideNametagMessage\022C\n\013player_" +
      "uuid\030\001 \001(\0132\".lunarclient.apollo.common.v" +
      "1.UuidR\nplayerUuid\022A\n\005lines\030\002 \003(\0132\'.luna" +
      "rclient.apollo.common.v1.ComponentB\002\030\001R\005" +
      "lines\0220\n\024adventure_json_lines\030\003 \003(\tR\022adv" +
      "entureJsonLines\"Z\n\023ResetNametagMessage\022C" +
      "\n\013player_uuid\030\001 \001(\0132\".lunarclient.apollo" +
      ".common.v1.UuidR\nplayerUuid\"\026\n\024ResetName" +
      "tagsMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          lunarclient.apollo.common.v1.ComponentOuterClass.getDescriptor(),
          lunarclient.apollo.common.v1.UuidOuterClass.getDescriptor(),
        });
    internal_static_lunarclient_apollo_nametag_v1_OverrideNametagMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_nametag_v1_OverrideNametagMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_nametag_v1_OverrideNametagMessage_descriptor,
        new java.lang.String[] { "PlayerUuid", "Lines", "AdventureJsonLines", });
    internal_static_lunarclient_apollo_nametag_v1_ResetNametagMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lunarclient_apollo_nametag_v1_ResetNametagMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_nametag_v1_ResetNametagMessage_descriptor,
        new java.lang.String[] { "PlayerUuid", });
    internal_static_lunarclient_apollo_nametag_v1_ResetNametagsMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lunarclient_apollo_nametag_v1_ResetNametagsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_nametag_v1_ResetNametagsMessage_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
    lunarclient.apollo.common.v1.ComponentOuterClass.getDescriptor();
    lunarclient.apollo.common.v1.UuidOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
