// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/configurable/v1/schema.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.configurable.v1;

@com.google.protobuf.Generated
public final class Schema {
  private Schema() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Schema.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigurableSettingsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.configurable.v1.ConfigurableSettings)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
     * @return Whether the lunarClientMod field is set.
     */
    boolean hasLunarClientMod();
    /**
     * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
     * @return The lunarClientMod.
     */
    java.lang.String getLunarClientMod();
    /**
     * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
     * @return The bytes for lunarClientMod.
     */
    com.google.protobuf.ByteString
        getLunarClientModBytes();

    /**
     * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
     * @return Whether the apolloModule field is set.
     */
    boolean hasApolloModule();
    /**
     * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
     * @return The apolloModule.
     */
    java.lang.String getApolloModule();
    /**
     * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
     * @return The bytes for apolloModule.
     */
    com.google.protobuf.ByteString
        getApolloModuleBytes();

    /**
     * <code>bool enable = 3 [json_name = "enable"];</code>
     * @return The enable.
     */
    boolean getEnable();

    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
     */
    int getPropertiesCount();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
     */
    boolean containsProperties(
        java.lang.String key);
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getProperties();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getPropertiesMap();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
     */
    /* nullable */
com.google.protobuf.Value getPropertiesOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.Value defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
     */
    com.google.protobuf.Value getPropertiesOrThrow(
        java.lang.String key);

    lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.TargetCase getTargetCase();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.configurable.v1.ConfigurableSettings}
   */
  public static final class ConfigurableSettings extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.configurable.v1.ConfigurableSettings)
      ConfigurableSettingsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ConfigurableSettings.class.getName());
    }
    // Use ConfigurableSettings.newBuilder() to construct.
    private ConfigurableSettings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ConfigurableSettings() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.class, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder.class);
    }

    private int targetCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object target_;
    public enum TargetCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      LUNAR_CLIENT_MOD(1),
      APOLLO_MODULE(2),
      TARGET_NOT_SET(0);
      private final int value;
      private TargetCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TargetCase valueOf(int value) {
        return forNumber(value);
      }

      public static TargetCase forNumber(int value) {
        switch (value) {
          case 1: return LUNAR_CLIENT_MOD;
          case 2: return APOLLO_MODULE;
          case 0: return TARGET_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TargetCase
    getTargetCase() {
      return TargetCase.forNumber(
          targetCase_);
    }

    public static final int LUNAR_CLIENT_MOD_FIELD_NUMBER = 1;
    /**
     * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
     * @return Whether the lunarClientMod field is set.
     */
    public boolean hasLunarClientMod() {
      return targetCase_ == 1;
    }
    /**
     * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
     * @return The lunarClientMod.
     */
    public java.lang.String getLunarClientMod() {
      java.lang.Object ref = "";
      if (targetCase_ == 1) {
        ref = target_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (targetCase_ == 1) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
     * @return The bytes for lunarClientMod.
     */
    public com.google.protobuf.ByteString
        getLunarClientModBytes() {
      java.lang.Object ref = "";
      if (targetCase_ == 1) {
        ref = target_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (targetCase_ == 1) {
          target_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APOLLO_MODULE_FIELD_NUMBER = 2;
    /**
     * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
     * @return Whether the apolloModule field is set.
     */
    public boolean hasApolloModule() {
      return targetCase_ == 2;
    }
    /**
     * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
     * @return The apolloModule.
     */
    public java.lang.String getApolloModule() {
      java.lang.Object ref = "";
      if (targetCase_ == 2) {
        ref = target_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (targetCase_ == 2) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
     * @return The bytes for apolloModule.
     */
    public com.google.protobuf.ByteString
        getApolloModuleBytes() {
      java.lang.Object ref = "";
      if (targetCase_ == 2) {
        ref = target_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (targetCase_ == 2) {
          target_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENABLE_FIELD_NUMBER = 3;
    private boolean enable_ = false;
    /**
     * <code>bool enable = 3 [json_name = "enable"];</code>
     * @return The enable.
     */
    @java.lang.Override
    public boolean getEnable() {
      return enable_;
    }

    public static final int PROPERTIES_FIELD_NUMBER = 4;
    private static final class PropertiesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Value>newDefaultInstance(
                  lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_PropertiesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Value.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Value> properties_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
    internalGetProperties() {
      if (properties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      return properties_;
    }
    public int getPropertiesCount() {
      return internalGetProperties().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
     */
    @java.lang.Override
    public boolean containsProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetProperties().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getProperties() {
      return getPropertiesMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getPropertiesMap() {
      return internalGetProperties().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.Value getPropertiesOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.Value defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetProperties().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Value getPropertiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetProperties().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (targetCase_ == 1) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, target_);
      }
      if (targetCase_ == 2) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, target_);
      }
      if (enable_ != false) {
        output.writeBool(3, enable_);
      }
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetProperties(),
          PropertiesDefaultEntryHolder.defaultEntry,
          4);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (targetCase_ == 1) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, target_);
      }
      if (targetCase_ == 2) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, target_);
      }
      if (enable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, enable_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> entry
           : internalGetProperties().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
        properties__ = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, properties__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings)) {
        return super.equals(obj);
      }
      lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings other = (lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings) obj;

      if (getEnable()
          != other.getEnable()) return false;
      if (!internalGetProperties().equals(
          other.internalGetProperties())) return false;
      if (!getTargetCase().equals(other.getTargetCase())) return false;
      switch (targetCase_) {
        case 1:
          if (!getLunarClientMod()
              .equals(other.getLunarClientMod())) return false;
          break;
        case 2:
          if (!getApolloModule()
              .equals(other.getApolloModule())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnable());
      if (!internalGetProperties().getMap().isEmpty()) {
        hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetProperties().hashCode();
      }
      switch (targetCase_) {
        case 1:
          hash = (37 * hash) + LUNAR_CLIENT_MOD_FIELD_NUMBER;
          hash = (53 * hash) + getLunarClientMod().hashCode();
          break;
        case 2:
          hash = (37 * hash) + APOLLO_MODULE_FIELD_NUMBER;
          hash = (53 * hash) + getApolloModule().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.configurable.v1.ConfigurableSettings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.configurable.v1.ConfigurableSettings)
        lunarclient.apollo.configurable.v1.Schema.ConfigurableSettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 4:
            return internalGetProperties();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableProperties();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.class, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder.class);
      }

      // Construct using lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        enable_ = false;
        internalGetMutableProperties().clear();
        targetCase_ = 0;
        target_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings getDefaultInstanceForType() {
        return lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings build() {
        lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings buildPartial() {
        lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings result = new lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.enable_ = enable_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.properties_ = internalGetProperties().build(PropertiesDefaultEntryHolder.defaultEntry);
        }
      }

      private void buildPartialOneofs(lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings result) {
        result.targetCase_ = targetCase_;
        result.target_ = this.target_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings) {
          return mergeFrom((lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings other) {
        if (other == lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.getDefaultInstance()) return this;
        if (other.getEnable() != false) {
          setEnable(other.getEnable());
        }
        internalGetMutableProperties().mergeFrom(
            other.internalGetProperties());
        bitField0_ |= 0x00000008;
        switch (other.getTargetCase()) {
          case LUNAR_CLIENT_MOD: {
            targetCase_ = 1;
            target_ = other.target_;
            onChanged();
            break;
          }
          case APOLLO_MODULE: {
            targetCase_ = 2;
            target_ = other.target_;
            onChanged();
            break;
          }
          case TARGET_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                targetCase_ = 1;
                target_ = s;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                targetCase_ = 2;
                target_ = s;
                break;
              } // case 18
              case 24: {
                enable_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
                properties__ = input.readMessage(
                    PropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableProperties().ensureBuilderMap().put(
                    properties__.getKey(), properties__.getValue());
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int targetCase_ = 0;
      private java.lang.Object target_;
      public TargetCase
          getTargetCase() {
        return TargetCase.forNumber(
            targetCase_);
      }

      public Builder clearTarget() {
        targetCase_ = 0;
        target_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      /**
       * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
       * @return Whether the lunarClientMod field is set.
       */
      @java.lang.Override
      public boolean hasLunarClientMod() {
        return targetCase_ == 1;
      }
      /**
       * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
       * @return The lunarClientMod.
       */
      @java.lang.Override
      public java.lang.String getLunarClientMod() {
        java.lang.Object ref = "";
        if (targetCase_ == 1) {
          ref = target_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (targetCase_ == 1) {
            target_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
       * @return The bytes for lunarClientMod.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLunarClientModBytes() {
        java.lang.Object ref = "";
        if (targetCase_ == 1) {
          ref = target_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (targetCase_ == 1) {
            target_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
       * @param value The lunarClientMod to set.
       * @return This builder for chaining.
       */
      public Builder setLunarClientMod(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        targetCase_ = 1;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLunarClientMod() {
        if (targetCase_ == 1) {
          targetCase_ = 0;
          target_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string lunar_client_mod = 1 [json_name = "lunarClientMod"];</code>
       * @param value The bytes for lunarClientMod to set.
       * @return This builder for chaining.
       */
      public Builder setLunarClientModBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        targetCase_ = 1;
        target_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
       * @return Whether the apolloModule field is set.
       */
      @java.lang.Override
      public boolean hasApolloModule() {
        return targetCase_ == 2;
      }
      /**
       * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
       * @return The apolloModule.
       */
      @java.lang.Override
      public java.lang.String getApolloModule() {
        java.lang.Object ref = "";
        if (targetCase_ == 2) {
          ref = target_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (targetCase_ == 2) {
            target_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
       * @return The bytes for apolloModule.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getApolloModuleBytes() {
        java.lang.Object ref = "";
        if (targetCase_ == 2) {
          ref = target_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (targetCase_ == 2) {
            target_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
       * @param value The apolloModule to set.
       * @return This builder for chaining.
       */
      public Builder setApolloModule(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        targetCase_ = 2;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
       * @return This builder for chaining.
       */
      public Builder clearApolloModule() {
        if (targetCase_ == 2) {
          targetCase_ = 0;
          target_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string apollo_module = 2 [json_name = "apolloModule"];</code>
       * @param value The bytes for apolloModule to set.
       * @return This builder for chaining.
       */
      public Builder setApolloModuleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        targetCase_ = 2;
        target_ = value;
        onChanged();
        return this;
      }

      private boolean enable_ ;
      /**
       * <code>bool enable = 3 [json_name = "enable"];</code>
       * @return The enable.
       */
      @java.lang.Override
      public boolean getEnable() {
        return enable_;
      }
      /**
       * <code>bool enable = 3 [json_name = "enable"];</code>
       * @param value The enable to set.
       * @return This builder for chaining.
       */
      public Builder setEnable(boolean value) {

        enable_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool enable = 3 [json_name = "enable"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEnable() {
        bitField0_ = (bitField0_ & ~0x00000004);
        enable_ = false;
        onChanged();
        return this;
      }

      private static final class PropertiesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value> {
        @java.lang.Override
        public com.google.protobuf.Value build(com.google.protobuf.ValueOrBuilder val) {
          if (val instanceof com.google.protobuf.Value) { return (com.google.protobuf.Value) val; }
          return ((com.google.protobuf.Value.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value> defaultEntry() {
          return PropertiesDefaultEntryHolder.defaultEntry;
        }
      };
      private static final PropertiesConverter propertiesConverter = new PropertiesConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value, com.google.protobuf.Value.Builder> properties_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value, com.google.protobuf.Value.Builder>
          internalGetProperties() {
        if (properties_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(propertiesConverter);
        }
        return properties_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value, com.google.protobuf.Value.Builder>
          internalGetMutableProperties() {
        if (properties_ == null) {
          properties_ = new com.google.protobuf.MapFieldBuilder<>(propertiesConverter);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return properties_;
      }
      public int getPropertiesCount() {
        return internalGetProperties().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
       */
      @java.lang.Override
      public boolean containsProperties(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetProperties().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getPropertiesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value> getProperties() {
        return getPropertiesMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.google.protobuf.Value> getPropertiesMap() {
        return internalGetProperties().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
       */
      @java.lang.Override
      public /* nullable */
com.google.protobuf.Value getPropertiesOrDefault(
          java.lang.String key,
          /* nullable */
com.google.protobuf.Value defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.ValueOrBuilder> map = internalGetMutableProperties().ensureBuilderMap();
        return map.containsKey(key) ? propertiesConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
       */
      @java.lang.Override
      public com.google.protobuf.Value getPropertiesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.ValueOrBuilder> map = internalGetMutableProperties().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return propertiesConverter.build(map.get(key));
      }
      public Builder clearProperties() {
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableProperties().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
       */
      public Builder removeProperties(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableProperties().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value>
          getMutableProperties() {
        bitField0_ |= 0x00000008;
        return internalGetMutableProperties().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
       */
      public Builder putProperties(
          java.lang.String key,
          com.google.protobuf.Value value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableProperties().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
       */
      public Builder putAllProperties(
          java.util.Map<java.lang.String, com.google.protobuf.Value> values) {
        for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableProperties().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; properties = 4 [json_name = "properties"];</code>
       */
      public com.google.protobuf.Value.Builder putPropertiesBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, com.google.protobuf.ValueOrBuilder> builderMap = internalGetMutableProperties().ensureBuilderMap();
        com.google.protobuf.ValueOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.google.protobuf.Value.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.google.protobuf.Value) {
          entry = ((com.google.protobuf.Value) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.google.protobuf.Value.Builder) entry;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.configurable.v1.ConfigurableSettings)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.configurable.v1.ConfigurableSettings)
    private static final lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings();
    }

    public static lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigurableSettings>
        PARSER = new com.google.protobuf.AbstractParser<ConfigurableSettings>() {
      @java.lang.Override
      public ConfigurableSettings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ConfigurableSettings> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigurableSettings> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OverrideConfigurableSettingsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.configurable.v1.OverrideConfigurableSettingsMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
     */
    java.util.List<lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings> 
        getConfigurableSettingsList();
    /**
     * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
     */
    lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings getConfigurableSettings(int index);
    /**
     * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
     */
    int getConfigurableSettingsCount();
    /**
     * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
     */
    java.util.List<? extends lunarclient.apollo.configurable.v1.Schema.ConfigurableSettingsOrBuilder> 
        getConfigurableSettingsOrBuilderList();
    /**
     * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
     */
    lunarclient.apollo.configurable.v1.Schema.ConfigurableSettingsOrBuilder getConfigurableSettingsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code lunarclient.apollo.configurable.v1.OverrideConfigurableSettingsMessage}
   */
  public static final class OverrideConfigurableSettingsMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.configurable.v1.OverrideConfigurableSettingsMessage)
      OverrideConfigurableSettingsMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        OverrideConfigurableSettingsMessage.class.getName());
    }
    // Use OverrideConfigurableSettingsMessage.newBuilder() to construct.
    private OverrideConfigurableSettingsMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OverrideConfigurableSettingsMessage() {
      configurableSettings_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_OverrideConfigurableSettingsMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_OverrideConfigurableSettingsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage.class, lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage.Builder.class);
    }

    public static final int CONFIGURABLE_SETTINGS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings> configurableSettings_;
    /**
     * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
     */
    @java.lang.Override
    public java.util.List<lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings> getConfigurableSettingsList() {
      return configurableSettings_;
    }
    /**
     * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends lunarclient.apollo.configurable.v1.Schema.ConfigurableSettingsOrBuilder> 
        getConfigurableSettingsOrBuilderList() {
      return configurableSettings_;
    }
    /**
     * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
     */
    @java.lang.Override
    public int getConfigurableSettingsCount() {
      return configurableSettings_.size();
    }
    /**
     * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings getConfigurableSettings(int index) {
      return configurableSettings_.get(index);
    }
    /**
     * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettingsOrBuilder getConfigurableSettingsOrBuilder(
        int index) {
      return configurableSettings_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < configurableSettings_.size(); i++) {
        output.writeMessage(1, configurableSettings_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < configurableSettings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, configurableSettings_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage other = (lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage) obj;

      if (!getConfigurableSettingsList()
          .equals(other.getConfigurableSettingsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getConfigurableSettingsCount() > 0) {
        hash = (37 * hash) + CONFIGURABLE_SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getConfigurableSettingsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.configurable.v1.OverrideConfigurableSettingsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.configurable.v1.OverrideConfigurableSettingsMessage)
        lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_OverrideConfigurableSettingsMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_OverrideConfigurableSettingsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage.class, lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (configurableSettingsBuilder_ == null) {
          configurableSettings_ = java.util.Collections.emptyList();
        } else {
          configurableSettings_ = null;
          configurableSettingsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.configurable.v1.Schema.internal_static_lunarclient_apollo_configurable_v1_OverrideConfigurableSettingsMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage getDefaultInstanceForType() {
        return lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage build() {
        lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage buildPartial() {
        lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage result = new lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage result) {
        if (configurableSettingsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            configurableSettings_ = java.util.Collections.unmodifiableList(configurableSettings_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.configurableSettings_ = configurableSettings_;
        } else {
          result.configurableSettings_ = configurableSettingsBuilder_.build();
        }
      }

      private void buildPartial0(lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage) {
          return mergeFrom((lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage other) {
        if (other == lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage.getDefaultInstance()) return this;
        if (configurableSettingsBuilder_ == null) {
          if (!other.configurableSettings_.isEmpty()) {
            if (configurableSettings_.isEmpty()) {
              configurableSettings_ = other.configurableSettings_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureConfigurableSettingsIsMutable();
              configurableSettings_.addAll(other.configurableSettings_);
            }
            onChanged();
          }
        } else {
          if (!other.configurableSettings_.isEmpty()) {
            if (configurableSettingsBuilder_.isEmpty()) {
              configurableSettingsBuilder_.dispose();
              configurableSettingsBuilder_ = null;
              configurableSettings_ = other.configurableSettings_;
              bitField0_ = (bitField0_ & ~0x00000001);
              configurableSettingsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetConfigurableSettingsFieldBuilder() : null;
            } else {
              configurableSettingsBuilder_.addAllMessages(other.configurableSettings_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings m =
                    input.readMessage(
                        lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.parser(),
                        extensionRegistry);
                if (configurableSettingsBuilder_ == null) {
                  ensureConfigurableSettingsIsMutable();
                  configurableSettings_.add(m);
                } else {
                  configurableSettingsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings> configurableSettings_ =
        java.util.Collections.emptyList();
      private void ensureConfigurableSettingsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          configurableSettings_ = new java.util.ArrayList<lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings>(configurableSettings_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettingsOrBuilder> configurableSettingsBuilder_;

      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public java.util.List<lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings> getConfigurableSettingsList() {
        if (configurableSettingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(configurableSettings_);
        } else {
          return configurableSettingsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public int getConfigurableSettingsCount() {
        if (configurableSettingsBuilder_ == null) {
          return configurableSettings_.size();
        } else {
          return configurableSettingsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings getConfigurableSettings(int index) {
        if (configurableSettingsBuilder_ == null) {
          return configurableSettings_.get(index);
        } else {
          return configurableSettingsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public Builder setConfigurableSettings(
          int index, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings value) {
        if (configurableSettingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigurableSettingsIsMutable();
          configurableSettings_.set(index, value);
          onChanged();
        } else {
          configurableSettingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public Builder setConfigurableSettings(
          int index, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder builderForValue) {
        if (configurableSettingsBuilder_ == null) {
          ensureConfigurableSettingsIsMutable();
          configurableSettings_.set(index, builderForValue.build());
          onChanged();
        } else {
          configurableSettingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public Builder addConfigurableSettings(lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings value) {
        if (configurableSettingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigurableSettingsIsMutable();
          configurableSettings_.add(value);
          onChanged();
        } else {
          configurableSettingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public Builder addConfigurableSettings(
          int index, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings value) {
        if (configurableSettingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigurableSettingsIsMutable();
          configurableSettings_.add(index, value);
          onChanged();
        } else {
          configurableSettingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public Builder addConfigurableSettings(
          lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder builderForValue) {
        if (configurableSettingsBuilder_ == null) {
          ensureConfigurableSettingsIsMutable();
          configurableSettings_.add(builderForValue.build());
          onChanged();
        } else {
          configurableSettingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public Builder addConfigurableSettings(
          int index, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder builderForValue) {
        if (configurableSettingsBuilder_ == null) {
          ensureConfigurableSettingsIsMutable();
          configurableSettings_.add(index, builderForValue.build());
          onChanged();
        } else {
          configurableSettingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public Builder addAllConfigurableSettings(
          java.lang.Iterable<? extends lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings> values) {
        if (configurableSettingsBuilder_ == null) {
          ensureConfigurableSettingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, configurableSettings_);
          onChanged();
        } else {
          configurableSettingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public Builder clearConfigurableSettings() {
        if (configurableSettingsBuilder_ == null) {
          configurableSettings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          configurableSettingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public Builder removeConfigurableSettings(int index) {
        if (configurableSettingsBuilder_ == null) {
          ensureConfigurableSettingsIsMutable();
          configurableSettings_.remove(index);
          onChanged();
        } else {
          configurableSettingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder getConfigurableSettingsBuilder(
          int index) {
        return internalGetConfigurableSettingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettingsOrBuilder getConfigurableSettingsOrBuilder(
          int index) {
        if (configurableSettingsBuilder_ == null) {
          return configurableSettings_.get(index);  } else {
          return configurableSettingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public java.util.List<? extends lunarclient.apollo.configurable.v1.Schema.ConfigurableSettingsOrBuilder> 
           getConfigurableSettingsOrBuilderList() {
        if (configurableSettingsBuilder_ != null) {
          return configurableSettingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(configurableSettings_);
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder addConfigurableSettingsBuilder() {
        return internalGetConfigurableSettingsFieldBuilder().addBuilder(
            lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.getDefaultInstance());
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder addConfigurableSettingsBuilder(
          int index) {
        return internalGetConfigurableSettingsFieldBuilder().addBuilder(
            index, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.getDefaultInstance());
      }
      /**
       * <code>repeated .lunarclient.apollo.configurable.v1.ConfigurableSettings configurable_settings = 1 [json_name = "configurableSettings"];</code>
       */
      public java.util.List<lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder> 
           getConfigurableSettingsBuilderList() {
        return internalGetConfigurableSettingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettingsOrBuilder> 
          internalGetConfigurableSettingsFieldBuilder() {
        if (configurableSettingsBuilder_ == null) {
          configurableSettingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettings.Builder, lunarclient.apollo.configurable.v1.Schema.ConfigurableSettingsOrBuilder>(
                  configurableSettings_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          configurableSettings_ = null;
        }
        return configurableSettingsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.configurable.v1.OverrideConfigurableSettingsMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.configurable.v1.OverrideConfigurableSettingsMessage)
    private static final lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage();
    }

    public static lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OverrideConfigurableSettingsMessage>
        PARSER = new com.google.protobuf.AbstractParser<OverrideConfigurableSettingsMessage>() {
      @java.lang.Override
      public OverrideConfigurableSettingsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OverrideConfigurableSettingsMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OverrideConfigurableSettingsMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.configurable.v1.Schema.OverrideConfigurableSettingsMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_PropertiesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_PropertiesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_configurable_v1_OverrideConfigurableSettingsMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_configurable_v1_OverrideConfigurableSettingsMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/lunarclient/apollo/configurable/v1/sch" +
      "ema.proto\022\"lunarclient.apollo.configurab" +
      "le.v1\032\034google/protobuf/struct.proto\"\314\002\n\024" +
      "ConfigurableSettings\022*\n\020lunar_client_mod" +
      "\030\001 \001(\tH\000R\016lunarClientMod\022%\n\rapollo_modul" +
      "e\030\002 \001(\tH\000R\014apolloModule\022\026\n\006enable\030\003 \001(\010R" +
      "\006enable\022h\n\nproperties\030\004 \003(\0132H.lunarclien" +
      "t.apollo.configurable.v1.ConfigurableSet" +
      "tings.PropertiesEntryR\nproperties\032U\n\017Pro" +
      "pertiesEntry\022\020\n\003key\030\001 \001(\tR\003key\022,\n\005value\030" +
      "\002 \001(\0132\026.google.protobuf.ValueR\005value:\0028\001" +
      "B\010\n\006target\"\224\001\n#OverrideConfigurableSetti" +
      "ngsMessage\022m\n\025configurable_settings\030\001 \003(" +
      "\01328.lunarclient.apollo.configurable.v1.C" +
      "onfigurableSettingsR\024configurableSetting" +
      "sb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_descriptor,
        new java.lang.String[] { "LunarClientMod", "ApolloModule", "Enable", "Properties", "Target", });
    internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_PropertiesEntry_descriptor =
      internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_descriptor.getNestedTypes().get(0);
    internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_configurable_v1_ConfigurableSettings_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lunarclient_apollo_configurable_v1_OverrideConfigurableSettingsMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lunarclient_apollo_configurable_v1_OverrideConfigurableSettingsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_configurable_v1_OverrideConfigurableSettingsMessage_descriptor,
        new java.lang.String[] { "ConfigurableSettings", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
