// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/staffmod/v1/schema.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.staffmod.v1;

@com.google.protobuf.Generated
public final class Schema {
  private Schema() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Schema.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code lunarclient.apollo.staffmod.v1.StaffMod}
   */
  public enum StaffMod
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STAFF_MOD_UNSPECIFIED = 0;</code>
     */
    STAFF_MOD_UNSPECIFIED(0),
    /**
     * <code>STAFF_MOD_XRAY = 1;</code>
     */
    STAFF_MOD_XRAY(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        StaffMod.class.getName());
    }
    /**
     * <code>STAFF_MOD_UNSPECIFIED = 0;</code>
     */
    public static final int STAFF_MOD_UNSPECIFIED_VALUE = 0;
    /**
     * <code>STAFF_MOD_XRAY = 1;</code>
     */
    public static final int STAFF_MOD_XRAY_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StaffMod valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StaffMod forNumber(int value) {
      switch (value) {
        case 0: return STAFF_MOD_UNSPECIFIED;
        case 1: return STAFF_MOD_XRAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StaffMod>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StaffMod> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StaffMod>() {
            public StaffMod findValueByNumber(int number) {
              return StaffMod.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lunarclient.apollo.staffmod.v1.Schema.getDescriptor().getEnumTypes().get(0);
    }

    private static final StaffMod[] VALUES = values();

    public static StaffMod valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StaffMod(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lunarclient.apollo.staffmod.v1.StaffMod)
  }

  public interface EnableStaffModsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.staffmod.v1.EnableStaffModsMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return A list containing the staffMods.
     */
    java.util.List<lunarclient.apollo.staffmod.v1.Schema.StaffMod> getStaffModsList();
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return The count of staffMods.
     */
    int getStaffModsCount();
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @param index The index of the element to return.
     * @return The staffMods at the given index.
     */
    lunarclient.apollo.staffmod.v1.Schema.StaffMod getStaffMods(int index);
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return A list containing the enum numeric values on the wire for staffMods.
     */
    java.util.List<java.lang.Integer>
    getStaffModsValueList();
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of staffMods at the given index.
     */
    int getStaffModsValue(int index);
  }
  /**
   * Protobuf type {@code lunarclient.apollo.staffmod.v1.EnableStaffModsMessage}
   */
  public static final class EnableStaffModsMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.staffmod.v1.EnableStaffModsMessage)
      EnableStaffModsMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        EnableStaffModsMessage.class.getName());
    }
    // Use EnableStaffModsMessage.newBuilder() to construct.
    private EnableStaffModsMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EnableStaffModsMessage() {
      staffMods_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.staffmod.v1.Schema.internal_static_lunarclient_apollo_staffmod_v1_EnableStaffModsMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.staffmod.v1.Schema.internal_static_lunarclient_apollo_staffmod_v1_EnableStaffModsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage.class, lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage.Builder.class);
    }

    public static final int STAFF_MODS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList staffMods_ =
        emptyIntList();
    private static final     com.google.protobuf.Internal.IntListAdapter.IntConverter<
        lunarclient.apollo.staffmod.v1.Schema.StaffMod> staffMods_converter_ =
            new com.google.protobuf.Internal.IntListAdapter.IntConverter<
                lunarclient.apollo.staffmod.v1.Schema.StaffMod>() {
              public lunarclient.apollo.staffmod.v1.Schema.StaffMod convert(int from) {
                lunarclient.apollo.staffmod.v1.Schema.StaffMod result = lunarclient.apollo.staffmod.v1.Schema.StaffMod.forNumber(from);
                return result == null ? lunarclient.apollo.staffmod.v1.Schema.StaffMod.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return A list containing the staffMods.
     */
    @java.lang.Override
    public java.util.List<lunarclient.apollo.staffmod.v1.Schema.StaffMod> getStaffModsList() {
      return new com.google.protobuf.Internal.IntListAdapter<
          lunarclient.apollo.staffmod.v1.Schema.StaffMod>(staffMods_, staffMods_converter_);
    }
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return The count of staffMods.
     */
    @java.lang.Override
    public int getStaffModsCount() {
      return staffMods_.size();
    }
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @param index The index of the element to return.
     * @return The staffMods at the given index.
     */
    @java.lang.Override
    public lunarclient.apollo.staffmod.v1.Schema.StaffMod getStaffMods(int index) {
      return staffMods_converter_.convert(staffMods_.getInt(index));
    }
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return A list containing the enum numeric values on the wire for staffMods.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getStaffModsValueList() {
      return staffMods_;
    }
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of staffMods at the given index.
     */
    @java.lang.Override
    public int getStaffModsValue(int index) {
      return staffMods_.getInt(index);
    }
    private int staffModsMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getStaffModsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(staffModsMemoizedSerializedSize);
      }
      for (int i = 0; i < staffMods_.size(); i++) {
        output.writeEnumNoTag(staffMods_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < staffMods_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(staffMods_.getInt(i));
        }
        size += dataSize;
        if (!getStaffModsList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }staffModsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage other = (lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage) obj;

      if (!staffMods_.equals(other.staffMods_)) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStaffModsCount() > 0) {
        hash = (37 * hash) + STAFF_MODS_FIELD_NUMBER;
        hash = (53 * hash) + staffMods_.hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.staffmod.v1.EnableStaffModsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.staffmod.v1.EnableStaffModsMessage)
        lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.staffmod.v1.Schema.internal_static_lunarclient_apollo_staffmod_v1_EnableStaffModsMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.staffmod.v1.Schema.internal_static_lunarclient_apollo_staffmod_v1_EnableStaffModsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage.class, lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        staffMods_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.staffmod.v1.Schema.internal_static_lunarclient_apollo_staffmod_v1_EnableStaffModsMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage getDefaultInstanceForType() {
        return lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage build() {
        lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage buildPartial() {
        lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage result = new lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          staffMods_.makeImmutable();
          result.staffMods_ = staffMods_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage) {
          return mergeFrom((lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage other) {
        if (other == lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage.getDefaultInstance()) return this;
        if (!other.staffMods_.isEmpty()) {
          if (staffMods_.isEmpty()) {
            staffMods_ = other.staffMods_;
            staffMods_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureStaffModsIsMutable();
            staffMods_.addAll(other.staffMods_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                ensureStaffModsIsMutable();
                staffMods_.addInt(tmpRaw);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureStaffModsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  staffMods_.addInt(input.readEnum());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList staffMods_ = emptyIntList();
      private void ensureStaffModsIsMutable() {
        if (!staffMods_.isModifiable()) {
          staffMods_ = makeMutableCopy(staffMods_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @return A list containing the staffMods.
       */
      public java.util.List<lunarclient.apollo.staffmod.v1.Schema.StaffMod> getStaffModsList() {
        return new com.google.protobuf.Internal.IntListAdapter<
            lunarclient.apollo.staffmod.v1.Schema.StaffMod>(staffMods_, staffMods_converter_);
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @return The count of staffMods.
       */
      public int getStaffModsCount() {
        return staffMods_.size();
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param index The index of the element to return.
       * @return The staffMods at the given index.
       */
      public lunarclient.apollo.staffmod.v1.Schema.StaffMod getStaffMods(int index) {
        return staffMods_converter_.convert(staffMods_.getInt(index));
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param index The index to set the value at.
       * @param value The staffMods to set.
       * @return This builder for chaining.
       */
      public Builder setStaffMods(
          int index, lunarclient.apollo.staffmod.v1.Schema.StaffMod value) {
        if (value == null) { throw new NullPointerException(); }
        ensureStaffModsIsMutable();
        staffMods_.setInt(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param value The staffMods to add.
       * @return This builder for chaining.
       */
      public Builder addStaffMods(lunarclient.apollo.staffmod.v1.Schema.StaffMod value) {
        if (value == null) { throw new NullPointerException(); }
        ensureStaffModsIsMutable();
        staffMods_.addInt(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param values The staffMods to add.
       * @return This builder for chaining.
       */
      public Builder addAllStaffMods(
          java.lang.Iterable<? extends lunarclient.apollo.staffmod.v1.Schema.StaffMod> values) {
        ensureStaffModsIsMutable();
        for (lunarclient.apollo.staffmod.v1.Schema.StaffMod value : values) {
          staffMods_.addInt(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStaffMods() {
        staffMods_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @return A list containing the enum numeric values on the wire for staffMods.
       */
      public java.util.List<java.lang.Integer>
      getStaffModsValueList() {
        staffMods_.makeImmutable();
        return staffMods_;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of staffMods at the given index.
       */
      public int getStaffModsValue(int index) {
        return staffMods_.getInt(index);
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param index The index to set the value at.
       * @param value The enum numeric value on the wire for staffMods to set.
       * @return This builder for chaining.
       */
      public Builder setStaffModsValue(
          int index, int value) {
        ensureStaffModsIsMutable();
        staffMods_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param value The enum numeric value on the wire for staffMods to add.
       * @return This builder for chaining.
       */
      public Builder addStaffModsValue(int value) {
        ensureStaffModsIsMutable();
        staffMods_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param values The enum numeric values on the wire for staffMods to add.
       * @return This builder for chaining.
       */
      public Builder addAllStaffModsValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureStaffModsIsMutable();
        for (int value : values) {
          staffMods_.addInt(value);
        }
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.staffmod.v1.EnableStaffModsMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.staffmod.v1.EnableStaffModsMessage)
    private static final lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage();
    }

    public static lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnableStaffModsMessage>
        PARSER = new com.google.protobuf.AbstractParser<EnableStaffModsMessage>() {
      @java.lang.Override
      public EnableStaffModsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EnableStaffModsMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnableStaffModsMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.staffmod.v1.Schema.EnableStaffModsMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DisableStaffModsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.staffmod.v1.DisableStaffModsMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return A list containing the staffMods.
     */
    java.util.List<lunarclient.apollo.staffmod.v1.Schema.StaffMod> getStaffModsList();
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return The count of staffMods.
     */
    int getStaffModsCount();
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @param index The index of the element to return.
     * @return The staffMods at the given index.
     */
    lunarclient.apollo.staffmod.v1.Schema.StaffMod getStaffMods(int index);
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return A list containing the enum numeric values on the wire for staffMods.
     */
    java.util.List<java.lang.Integer>
    getStaffModsValueList();
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of staffMods at the given index.
     */
    int getStaffModsValue(int index);
  }
  /**
   * Protobuf type {@code lunarclient.apollo.staffmod.v1.DisableStaffModsMessage}
   */
  public static final class DisableStaffModsMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.staffmod.v1.DisableStaffModsMessage)
      DisableStaffModsMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        DisableStaffModsMessage.class.getName());
    }
    // Use DisableStaffModsMessage.newBuilder() to construct.
    private DisableStaffModsMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DisableStaffModsMessage() {
      staffMods_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.staffmod.v1.Schema.internal_static_lunarclient_apollo_staffmod_v1_DisableStaffModsMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.staffmod.v1.Schema.internal_static_lunarclient_apollo_staffmod_v1_DisableStaffModsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage.class, lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage.Builder.class);
    }

    public static final int STAFF_MODS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList staffMods_ =
        emptyIntList();
    private static final     com.google.protobuf.Internal.IntListAdapter.IntConverter<
        lunarclient.apollo.staffmod.v1.Schema.StaffMod> staffMods_converter_ =
            new com.google.protobuf.Internal.IntListAdapter.IntConverter<
                lunarclient.apollo.staffmod.v1.Schema.StaffMod>() {
              public lunarclient.apollo.staffmod.v1.Schema.StaffMod convert(int from) {
                lunarclient.apollo.staffmod.v1.Schema.StaffMod result = lunarclient.apollo.staffmod.v1.Schema.StaffMod.forNumber(from);
                return result == null ? lunarclient.apollo.staffmod.v1.Schema.StaffMod.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return A list containing the staffMods.
     */
    @java.lang.Override
    public java.util.List<lunarclient.apollo.staffmod.v1.Schema.StaffMod> getStaffModsList() {
      return new com.google.protobuf.Internal.IntListAdapter<
          lunarclient.apollo.staffmod.v1.Schema.StaffMod>(staffMods_, staffMods_converter_);
    }
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return The count of staffMods.
     */
    @java.lang.Override
    public int getStaffModsCount() {
      return staffMods_.size();
    }
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @param index The index of the element to return.
     * @return The staffMods at the given index.
     */
    @java.lang.Override
    public lunarclient.apollo.staffmod.v1.Schema.StaffMod getStaffMods(int index) {
      return staffMods_converter_.convert(staffMods_.getInt(index));
    }
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @return A list containing the enum numeric values on the wire for staffMods.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getStaffModsValueList() {
      return staffMods_;
    }
    /**
     * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of staffMods at the given index.
     */
    @java.lang.Override
    public int getStaffModsValue(int index) {
      return staffMods_.getInt(index);
    }
    private int staffModsMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getStaffModsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(staffModsMemoizedSerializedSize);
      }
      for (int i = 0; i < staffMods_.size(); i++) {
        output.writeEnumNoTag(staffMods_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < staffMods_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(staffMods_.getInt(i));
        }
        size += dataSize;
        if (!getStaffModsList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }staffModsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage other = (lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage) obj;

      if (!staffMods_.equals(other.staffMods_)) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStaffModsCount() > 0) {
        hash = (37 * hash) + STAFF_MODS_FIELD_NUMBER;
        hash = (53 * hash) + staffMods_.hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.staffmod.v1.DisableStaffModsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.staffmod.v1.DisableStaffModsMessage)
        lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.staffmod.v1.Schema.internal_static_lunarclient_apollo_staffmod_v1_DisableStaffModsMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.staffmod.v1.Schema.internal_static_lunarclient_apollo_staffmod_v1_DisableStaffModsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage.class, lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        staffMods_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.staffmod.v1.Schema.internal_static_lunarclient_apollo_staffmod_v1_DisableStaffModsMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage getDefaultInstanceForType() {
        return lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage build() {
        lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage buildPartial() {
        lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage result = new lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          staffMods_.makeImmutable();
          result.staffMods_ = staffMods_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage) {
          return mergeFrom((lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage other) {
        if (other == lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage.getDefaultInstance()) return this;
        if (!other.staffMods_.isEmpty()) {
          if (staffMods_.isEmpty()) {
            staffMods_ = other.staffMods_;
            staffMods_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureStaffModsIsMutable();
            staffMods_.addAll(other.staffMods_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                ensureStaffModsIsMutable();
                staffMods_.addInt(tmpRaw);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureStaffModsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  staffMods_.addInt(input.readEnum());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList staffMods_ = emptyIntList();
      private void ensureStaffModsIsMutable() {
        if (!staffMods_.isModifiable()) {
          staffMods_ = makeMutableCopy(staffMods_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @return A list containing the staffMods.
       */
      public java.util.List<lunarclient.apollo.staffmod.v1.Schema.StaffMod> getStaffModsList() {
        return new com.google.protobuf.Internal.IntListAdapter<
            lunarclient.apollo.staffmod.v1.Schema.StaffMod>(staffMods_, staffMods_converter_);
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @return The count of staffMods.
       */
      public int getStaffModsCount() {
        return staffMods_.size();
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param index The index of the element to return.
       * @return The staffMods at the given index.
       */
      public lunarclient.apollo.staffmod.v1.Schema.StaffMod getStaffMods(int index) {
        return staffMods_converter_.convert(staffMods_.getInt(index));
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param index The index to set the value at.
       * @param value The staffMods to set.
       * @return This builder for chaining.
       */
      public Builder setStaffMods(
          int index, lunarclient.apollo.staffmod.v1.Schema.StaffMod value) {
        if (value == null) { throw new NullPointerException(); }
        ensureStaffModsIsMutable();
        staffMods_.setInt(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param value The staffMods to add.
       * @return This builder for chaining.
       */
      public Builder addStaffMods(lunarclient.apollo.staffmod.v1.Schema.StaffMod value) {
        if (value == null) { throw new NullPointerException(); }
        ensureStaffModsIsMutable();
        staffMods_.addInt(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param values The staffMods to add.
       * @return This builder for chaining.
       */
      public Builder addAllStaffMods(
          java.lang.Iterable<? extends lunarclient.apollo.staffmod.v1.Schema.StaffMod> values) {
        ensureStaffModsIsMutable();
        for (lunarclient.apollo.staffmod.v1.Schema.StaffMod value : values) {
          staffMods_.addInt(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStaffMods() {
        staffMods_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @return A list containing the enum numeric values on the wire for staffMods.
       */
      public java.util.List<java.lang.Integer>
      getStaffModsValueList() {
        staffMods_.makeImmutable();
        return staffMods_;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of staffMods at the given index.
       */
      public int getStaffModsValue(int index) {
        return staffMods_.getInt(index);
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param index The index to set the value at.
       * @param value The enum numeric value on the wire for staffMods to set.
       * @return This builder for chaining.
       */
      public Builder setStaffModsValue(
          int index, int value) {
        ensureStaffModsIsMutable();
        staffMods_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param value The enum numeric value on the wire for staffMods to add.
       * @return This builder for chaining.
       */
      public Builder addStaffModsValue(int value) {
        ensureStaffModsIsMutable();
        staffMods_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.staffmod.v1.StaffMod staff_mods = 1 [json_name = "staffMods"];</code>
       * @param values The enum numeric values on the wire for staffMods to add.
       * @return This builder for chaining.
       */
      public Builder addAllStaffModsValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureStaffModsIsMutable();
        for (int value : values) {
          staffMods_.addInt(value);
        }
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.staffmod.v1.DisableStaffModsMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.staffmod.v1.DisableStaffModsMessage)
    private static final lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage();
    }

    public static lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DisableStaffModsMessage>
        PARSER = new com.google.protobuf.AbstractParser<DisableStaffModsMessage>() {
      @java.lang.Override
      public DisableStaffModsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DisableStaffModsMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DisableStaffModsMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.staffmod.v1.Schema.DisableStaffModsMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_staffmod_v1_EnableStaffModsMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_staffmod_v1_EnableStaffModsMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_staffmod_v1_DisableStaffModsMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_staffmod_v1_DisableStaffModsMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+lunarclient/apollo/staffmod/v1/schema." +
      "proto\022\036lunarclient.apollo.staffmod.v1\"a\n" +
      "\026EnableStaffModsMessage\022G\n\nstaff_mods\030\001 " +
      "\003(\0162(.lunarclient.apollo.staffmod.v1.Sta" +
      "ffModR\tstaffMods\"b\n\027DisableStaffModsMess" +
      "age\022G\n\nstaff_mods\030\001 \003(\0162(.lunarclient.ap" +
      "ollo.staffmod.v1.StaffModR\tstaffMods*9\n\010" +
      "StaffMod\022\031\n\025STAFF_MOD_UNSPECIFIED\020\000\022\022\n\016S" +
      "TAFF_MOD_XRAY\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lunarclient_apollo_staffmod_v1_EnableStaffModsMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_staffmod_v1_EnableStaffModsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_staffmod_v1_EnableStaffModsMessage_descriptor,
        new java.lang.String[] { "StaffMods", });
    internal_static_lunarclient_apollo_staffmod_v1_DisableStaffModsMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lunarclient_apollo_staffmod_v1_DisableStaffModsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_staffmod_v1_DisableStaffModsMessage_descriptor,
        new java.lang.String[] { "StaffMods", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
