// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/evnt/v1/hearttexture.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.evnt.v1;

@com.google.protobuf.Generated
public final class Hearttexture {
  private Hearttexture() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Hearttexture.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OverrideHeartTextureMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.evnt.v1.OverrideHeartTextureMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 location_x = 1 [json_name = "locationX"];</code>
     * @return The locationX.
     */
    int getLocationX();

    /**
     * <code>bool hardcore = 2 [json_name = "hardcore"];</code>
     * @return The hardcore.
     */
    boolean getHardcore();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.evnt.v1.OverrideHeartTextureMessage}
   */
  public static final class OverrideHeartTextureMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.evnt.v1.OverrideHeartTextureMessage)
      OverrideHeartTextureMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        OverrideHeartTextureMessage.class.getName());
    }
    // Use OverrideHeartTextureMessage.newBuilder() to construct.
    private OverrideHeartTextureMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OverrideHeartTextureMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.evnt.v1.Hearttexture.internal_static_lunarclient_apollo_evnt_v1_OverrideHeartTextureMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.evnt.v1.Hearttexture.internal_static_lunarclient_apollo_evnt_v1_OverrideHeartTextureMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage.class, lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage.Builder.class);
    }

    public static final int LOCATION_X_FIELD_NUMBER = 1;
    private int locationX_ = 0;
    /**
     * <code>int32 location_x = 1 [json_name = "locationX"];</code>
     * @return The locationX.
     */
    @java.lang.Override
    public int getLocationX() {
      return locationX_;
    }

    public static final int HARDCORE_FIELD_NUMBER = 2;
    private boolean hardcore_ = false;
    /**
     * <code>bool hardcore = 2 [json_name = "hardcore"];</code>
     * @return The hardcore.
     */
    @java.lang.Override
    public boolean getHardcore() {
      return hardcore_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (locationX_ != 0) {
        output.writeInt32(1, locationX_);
      }
      if (hardcore_ != false) {
        output.writeBool(2, hardcore_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (locationX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, locationX_);
      }
      if (hardcore_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, hardcore_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage other = (lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage) obj;

      if (getLocationX()
          != other.getLocationX()) return false;
      if (getHardcore()
          != other.getHardcore()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCATION_X_FIELD_NUMBER;
      hash = (53 * hash) + getLocationX();
      hash = (37 * hash) + HARDCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHardcore());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.evnt.v1.OverrideHeartTextureMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.evnt.v1.OverrideHeartTextureMessage)
        lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.evnt.v1.Hearttexture.internal_static_lunarclient_apollo_evnt_v1_OverrideHeartTextureMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.evnt.v1.Hearttexture.internal_static_lunarclient_apollo_evnt_v1_OverrideHeartTextureMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage.class, lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        locationX_ = 0;
        hardcore_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.evnt.v1.Hearttexture.internal_static_lunarclient_apollo_evnt_v1_OverrideHeartTextureMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage getDefaultInstanceForType() {
        return lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage build() {
        lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage buildPartial() {
        lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage result = new lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.locationX_ = locationX_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.hardcore_ = hardcore_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage) {
          return mergeFrom((lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage other) {
        if (other == lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage.getDefaultInstance()) return this;
        if (other.getLocationX() != 0) {
          setLocationX(other.getLocationX());
        }
        if (other.getHardcore() != false) {
          setHardcore(other.getHardcore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                locationX_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                hardcore_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int locationX_ ;
      /**
       * <code>int32 location_x = 1 [json_name = "locationX"];</code>
       * @return The locationX.
       */
      @java.lang.Override
      public int getLocationX() {
        return locationX_;
      }
      /**
       * <code>int32 location_x = 1 [json_name = "locationX"];</code>
       * @param value The locationX to set.
       * @return This builder for chaining.
       */
      public Builder setLocationX(int value) {

        locationX_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 location_x = 1 [json_name = "locationX"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLocationX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        locationX_ = 0;
        onChanged();
        return this;
      }

      private boolean hardcore_ ;
      /**
       * <code>bool hardcore = 2 [json_name = "hardcore"];</code>
       * @return The hardcore.
       */
      @java.lang.Override
      public boolean getHardcore() {
        return hardcore_;
      }
      /**
       * <code>bool hardcore = 2 [json_name = "hardcore"];</code>
       * @param value The hardcore to set.
       * @return This builder for chaining.
       */
      public Builder setHardcore(boolean value) {

        hardcore_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool hardcore = 2 [json_name = "hardcore"];</code>
       * @return This builder for chaining.
       */
      public Builder clearHardcore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hardcore_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.evnt.v1.OverrideHeartTextureMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.evnt.v1.OverrideHeartTextureMessage)
    private static final lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage();
    }

    public static lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OverrideHeartTextureMessage>
        PARSER = new com.google.protobuf.AbstractParser<OverrideHeartTextureMessage>() {
      @java.lang.Override
      public OverrideHeartTextureMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OverrideHeartTextureMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OverrideHeartTextureMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.evnt.v1.Hearttexture.OverrideHeartTextureMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResetHeartTextureMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.evnt.v1.ResetHeartTextureMessage)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * nothing
   * </pre>
   *
   * Protobuf type {@code lunarclient.apollo.evnt.v1.ResetHeartTextureMessage}
   */
  public static final class ResetHeartTextureMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.evnt.v1.ResetHeartTextureMessage)
      ResetHeartTextureMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ResetHeartTextureMessage.class.getName());
    }
    // Use ResetHeartTextureMessage.newBuilder() to construct.
    private ResetHeartTextureMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResetHeartTextureMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.evnt.v1.Hearttexture.internal_static_lunarclient_apollo_evnt_v1_ResetHeartTextureMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.evnt.v1.Hearttexture.internal_static_lunarclient_apollo_evnt_v1_ResetHeartTextureMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage.class, lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage other = (lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * nothing
     * </pre>
     *
     * Protobuf type {@code lunarclient.apollo.evnt.v1.ResetHeartTextureMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.evnt.v1.ResetHeartTextureMessage)
        lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.evnt.v1.Hearttexture.internal_static_lunarclient_apollo_evnt_v1_ResetHeartTextureMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.evnt.v1.Hearttexture.internal_static_lunarclient_apollo_evnt_v1_ResetHeartTextureMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage.class, lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.evnt.v1.Hearttexture.internal_static_lunarclient_apollo_evnt_v1_ResetHeartTextureMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage getDefaultInstanceForType() {
        return lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage build() {
        lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage buildPartial() {
        lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage result = new lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage) {
          return mergeFrom((lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage other) {
        if (other == lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.evnt.v1.ResetHeartTextureMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.evnt.v1.ResetHeartTextureMessage)
    private static final lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage();
    }

    public static lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResetHeartTextureMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResetHeartTextureMessage>() {
      @java.lang.Override
      public ResetHeartTextureMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResetHeartTextureMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResetHeartTextureMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.evnt.v1.Hearttexture.ResetHeartTextureMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_evnt_v1_OverrideHeartTextureMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_evnt_v1_OverrideHeartTextureMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_evnt_v1_ResetHeartTextureMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_evnt_v1_ResetHeartTextureMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-lunarclient/apollo/evnt/v1/hearttextur" +
      "e.proto\022\032lunarclient.apollo.evnt.v1\"X\n\033O" +
      "verrideHeartTextureMessage\022\035\n\nlocation_x" +
      "\030\001 \001(\005R\tlocationX\022\032\n\010hardcore\030\002 \001(\010R\010har" +
      "dcore\"\032\n\030ResetHeartTextureMessageb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lunarclient_apollo_evnt_v1_OverrideHeartTextureMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_evnt_v1_OverrideHeartTextureMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_evnt_v1_OverrideHeartTextureMessage_descriptor,
        new java.lang.String[] { "LocationX", "Hardcore", });
    internal_static_lunarclient_apollo_evnt_v1_ResetHeartTextureMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lunarclient_apollo_evnt_v1_ResetHeartTextureMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_evnt_v1_ResetHeartTextureMessage_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
