// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/stopwatch/v1/schema.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.stopwatch.v1;

@com.google.protobuf.Generated
public final class Schema {
  private Schema() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Schema.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StartStopwatchMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.stopwatch.v1.StartStopwatchMessage)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * nothing
   * </pre>
   *
   * Protobuf type {@code lunarclient.apollo.stopwatch.v1.StartStopwatchMessage}
   */
  public static final class StartStopwatchMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.stopwatch.v1.StartStopwatchMessage)
      StartStopwatchMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        StartStopwatchMessage.class.getName());
    }
    // Use StartStopwatchMessage.newBuilder() to construct.
    private StartStopwatchMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private StartStopwatchMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_StartStopwatchMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_StartStopwatchMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage.class, lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage other = (lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * nothing
     * </pre>
     *
     * Protobuf type {@code lunarclient.apollo.stopwatch.v1.StartStopwatchMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.stopwatch.v1.StartStopwatchMessage)
        lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_StartStopwatchMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_StartStopwatchMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage.class, lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_StartStopwatchMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage getDefaultInstanceForType() {
        return lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage build() {
        lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage buildPartial() {
        lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage result = new lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage) {
          return mergeFrom((lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage other) {
        if (other == lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.stopwatch.v1.StartStopwatchMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.stopwatch.v1.StartStopwatchMessage)
    private static final lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage();
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StartStopwatchMessage>
        PARSER = new com.google.protobuf.AbstractParser<StartStopwatchMessage>() {
      @java.lang.Override
      public StartStopwatchMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StartStopwatchMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StartStopwatchMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.stopwatch.v1.Schema.StartStopwatchMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StopStopwatchMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.stopwatch.v1.StopStopwatchMessage)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * nothing
   * </pre>
   *
   * Protobuf type {@code lunarclient.apollo.stopwatch.v1.StopStopwatchMessage}
   */
  public static final class StopStopwatchMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.stopwatch.v1.StopStopwatchMessage)
      StopStopwatchMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        StopStopwatchMessage.class.getName());
    }
    // Use StopStopwatchMessage.newBuilder() to construct.
    private StopStopwatchMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private StopStopwatchMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_StopStopwatchMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_StopStopwatchMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage.class, lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage other = (lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * nothing
     * </pre>
     *
     * Protobuf type {@code lunarclient.apollo.stopwatch.v1.StopStopwatchMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.stopwatch.v1.StopStopwatchMessage)
        lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_StopStopwatchMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_StopStopwatchMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage.class, lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_StopStopwatchMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage getDefaultInstanceForType() {
        return lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage build() {
        lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage buildPartial() {
        lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage result = new lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage) {
          return mergeFrom((lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage other) {
        if (other == lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.stopwatch.v1.StopStopwatchMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.stopwatch.v1.StopStopwatchMessage)
    private static final lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage();
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StopStopwatchMessage>
        PARSER = new com.google.protobuf.AbstractParser<StopStopwatchMessage>() {
      @java.lang.Override
      public StopStopwatchMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StopStopwatchMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StopStopwatchMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.stopwatch.v1.Schema.StopStopwatchMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResetStopwatchMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.stopwatch.v1.ResetStopwatchMessage)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * nothing
   * </pre>
   *
   * Protobuf type {@code lunarclient.apollo.stopwatch.v1.ResetStopwatchMessage}
   */
  public static final class ResetStopwatchMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.stopwatch.v1.ResetStopwatchMessage)
      ResetStopwatchMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ResetStopwatchMessage.class.getName());
    }
    // Use ResetStopwatchMessage.newBuilder() to construct.
    private ResetStopwatchMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResetStopwatchMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_ResetStopwatchMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_ResetStopwatchMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage.class, lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage)) {
        return super.equals(obj);
      }
      lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage other = (lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * nothing
     * </pre>
     *
     * Protobuf type {@code lunarclient.apollo.stopwatch.v1.ResetStopwatchMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.stopwatch.v1.ResetStopwatchMessage)
        lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_ResetStopwatchMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_ResetStopwatchMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage.class, lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage.Builder.class);
      }

      // Construct using lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.stopwatch.v1.Schema.internal_static_lunarclient_apollo_stopwatch_v1_ResetStopwatchMessage_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage getDefaultInstanceForType() {
        return lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage build() {
        lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage buildPartial() {
        lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage result = new lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage) {
          return mergeFrom((lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage other) {
        if (other == lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.stopwatch.v1.ResetStopwatchMessage)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.stopwatch.v1.ResetStopwatchMessage)
    private static final lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage();
    }

    public static lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResetStopwatchMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResetStopwatchMessage>() {
      @java.lang.Override
      public ResetStopwatchMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResetStopwatchMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResetStopwatchMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.stopwatch.v1.Schema.ResetStopwatchMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_stopwatch_v1_StartStopwatchMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_stopwatch_v1_StartStopwatchMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_stopwatch_v1_StopStopwatchMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_stopwatch_v1_StopStopwatchMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_stopwatch_v1_ResetStopwatchMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_stopwatch_v1_ResetStopwatchMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,lunarclient/apollo/stopwatch/v1/schema" +
      ".proto\022\037lunarclient.apollo.stopwatch.v1\"" +
      "\027\n\025StartStopwatchMessage\"\026\n\024StopStopwatc" +
      "hMessage\"\027\n\025ResetStopwatchMessageb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lunarclient_apollo_stopwatch_v1_StartStopwatchMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_stopwatch_v1_StartStopwatchMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_stopwatch_v1_StartStopwatchMessage_descriptor,
        new java.lang.String[] { });
    internal_static_lunarclient_apollo_stopwatch_v1_StopStopwatchMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lunarclient_apollo_stopwatch_v1_StopStopwatchMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_stopwatch_v1_StopStopwatchMessage_descriptor,
        new java.lang.String[] { });
    internal_static_lunarclient_apollo_stopwatch_v1_ResetStopwatchMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lunarclient_apollo_stopwatch_v1_ResetStopwatchMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_stopwatch_v1_ResetStopwatchMessage_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
